name: jobgo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.10.8 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Supabase SDK cho Flutter
  supabase_flutter: ^2.0.0
  # Bloc để quản lý state
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  app_links: ^6.0.0
  file_picker: ^10.3.10
  provider: ^6.1.5+1
  image_picker: ^1.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/icons/google.png
    # - assets/icons/facebook.jpg
    # - assets/images/role_candidate1.jpg
    # - assets/images/role_employee.jpg
    - assets/icons/
    - assets/images/
    - .env
