final Map<String, String> englishStrings = {
  // Auth
  'email': 'Email',
  'password': 'Password',
  'confirmPassword': 'Confirm Password',
  'login': 'Login',
  'register': 'Register',
  'logout': 'Logout',
  'forgotPassword': 'Forgot Password?',
  'resetPassword': 'Reset Password',
  'signUp': 'Sign Up',
  'signIn': 'Sign In',
  'signInWithGoogle': 'Sign In with Google',
  'signInWithFacebook': 'Sign In with Facebook',
  'alreadyHaveAccount': 'Already have an account?',
  'dontHaveAccount': 'Don\'t have an account?',
  'invalidEmail': 'Please enter a valid email',
  'passwordTooShort': 'Password must be at least 6 characters',
  'passwordsDoNotMatch': 'Passwords do not match',
  'emailAlreadyExists': 'Email already exists',
  'invalidCredentials': 'Invalid email or password',
  'loginSuccess': 'Login successful',
  'registerSuccess': 'Registration successful',
  'logoutSuccess': 'Logout successful',
  'emailAddressHint': 'Email Address',
  'passwordHint': 'Password',
  'rememberMe': 'Remember me',
  'welcomeBack': 'Welcome Back',
  'signInToContinue': 'Sign in to continue your job search',
  'dontHaveAccountQuestion': 'Don\'t have an account?',
  'loginError': 'Login failed',
  'emailRequired': 'Email is required',
  'invalidEmailFormat': 'Invalid email format',
  'passwordRequired': 'Password is required',

  // Profile
  'profile': 'Profile',
  'editProfile': 'Edit Profile',
  'fullName': 'Full Name',
  'phoneNumber': 'Phone Number',
  'address': 'Address',
  'bio': 'Bio',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'info': 'Info',
  'favorites': 'Favorites',
  'profileUpdated': 'Profile updated successfully',
  'messagesTitle': 'Messages',
  'fromRecruiters': 'From recruiters',
  'searchMessagesHint': 'Search messages, companies...',
  'unreadFilter': 'Unread',
  'urgentFilter': 'Urgent',
  'interviewedFilter': 'Interviewed',
  'savedFilter': 'Saved',
  'pinnedLabel': 'Pinned',
  'allLabel': 'All',
  'respondsIn24h': 'Responds in 24h',
  'resume': 'Resume',
  'uploadResume': 'Upload Resume',
  'replaceResume': 'Replace Resume',
  'deleteResume': 'Delete Resume',
  'viewResume': 'View Resume',
  'skills': 'Skills',
  'experience': 'Experience',
  'education': 'Education',
  'resumeDocuments': 'Resume & Documents',
  'resumeFiles': 'FILES',
  'browseFiles': 'Browse Files',
  'uploadThankYou': 'Upload successful',
  'uploadFailed': 'Upload failed',
  'replaceFailed': 'Replace failed',
  'deleteSuccess': 'Delete successful',
  'setDefaultSuccess': 'Set as default successful',
  'replaceSuccess': 'Replaced successfully',

  // Jobs
  'jobs': 'Jobs',
  'jobTitle': 'Job Title',
  'company': 'Company',
  'location': 'Location',
  'salary': 'Salary',
  'description': 'Description',
  'requirements': 'Requirements',
  'applyJob': 'Apply for Job',
  'appliedJobs': 'Applied Jobs',
  'savedJobs': 'Saved Jobs',
  'jobDetails': 'Job Details',
  'noJobsFound': 'No jobs found',
  'applySuccess': 'Application submitted successfully',
  'apply': 'Apply',
  'favoriteJobs': 'Favorite Jobs',

  // Common
  'home': 'Home',
  'search': 'Search',
  'settings': 'Settings',
  'language': 'Language',
  'selectLanguage': 'Select language',
  'notifications': 'Notifications',
  'help': 'Help',
  'about': 'About',
  'version': 'Version',
  'loading': 'Loading...',
  'error': 'Error',
  'errorMessage': 'Error: ',
  'success': 'Success',
  'tryAgain': 'Try Again',
  'noInternetConnection': 'No Internet Connection',
  'somethingWentWrong': 'Something went wrong',
  'close': 'Close',
  'open': 'Open',
  'yes': 'Yes',
  'no': 'No',
  'ok': 'OK',
  'contactUs': 'Contact Us',
  'privacyPolicy': 'Privacy Policy',
  'termsOfService': 'Terms of Service',
  'helpCenter': 'Help Center',
  'changePassword': 'Change Password',
  'pushNotifications': 'Push Notifications',
  'account': 'ACCOUNT',
  'privacy': 'PRIVACY',
  'support': 'SUPPORT',
  'desiredPosition': 'Desired Position',
  'yearsOfExperience': 'Years of Experience',
  'positionDesiredTitle': 'Position Desired: ',
  'exitApplication': 'Exit Application',
  'coverLetter': 'Cover Letter',
  'applySuccessMessage': 'Application submitted successfully',
  'stepOfThree': 'STEP 1 OF 3',
  'chooseYourRole': 'Choose your role',
  'selectHowToUse': 'Select how you want to use the platform',
  'iAmCandidate': 'I am a Candidate',
  'candidateDescription':
      'I\'m looking for new career opportunities and want to showcase my talent.',
  'iAmEmployer': 'I am an Employer',
  'employerDescription':
      'I\'m looking to hire talented candidates for my company.',
  'next': 'Next',
  'back': 'Back',
  'selectRole': 'Please select a role to continue',
  'uploadNewResume': 'Upload a new resume',
  'uploadFileSize': 'PDF, DOCX up to 10MB',
  // Register Info Page
  'fullNameHint': 'Full Name',
  'fullNameRequired': 'Full name is required',
  'fullNameLength': 'Full name must be at least 2 characters',
  'emailAddressRequired': 'Email is required',
  'passwordMinLength': 'Password must be at least 6 characters',
  'confirmPasswordLabel': 'Confirm Password',
  'confirmPasswordHint': 'Confirm Password',
  'passwordMismatch': 'Passwords do not match',
  // Register Verify Email
  'stepOfThreeMsg': 'STEP 3 OF 3',
  'otpVerification': 'OTP Verification',
  'emailVerificationMessage': 'We sent a confirmation link to',
  'clickLinkMessage': 'Click the link in your email to activate your account.',
  'confirmedEmail': "I've confirmed my email",
  'didNotReceiveEmail': "Didn't receive the email?",
  'resendEmail': 'Resend email',
  'requestNewCode': 'Request new code in',
  'verificationSuccess': 'Email verified successfully!',
  'verificationFailed': 'Email verification failed',
  'resendFailed': 'Failed to resend email',

  // Job Search & Details
  'searchJobTitle': 'Search job title or keyword',
  'clearFilters': 'Clear filters',
  'noJobsMatch': 'No jobs match your filters.',
  'jobsFound': 'jobs found',
  'filters': 'Filters',
  'mostRelevant': 'Most Relevant',
  'alreadyApplied': 'Already Applied',
  'applyNow': 'Apply Now',
  'jobClosed': 'Job Closed',

  // Apply Job
  'applyForJob': 'Apply for Job',
  'selectCV': 'Select CV',
  'chooseResumeForApplication':
      'Choose the resume you\'d like to use for this application.',
  'noCVFound': 'No CV found in your profile',
  'pleaseUploadCVBeforeApplying':
      'Please upload a CV to your profile before applying.',
  'resumeSelection': 'Resume Selection',
  'finalReview': 'FINAL REVIEW',
  'step1Of2': 'STEP 1 OF 2',
  'step2Of2': 'Step 2 of 2',
  'successfullyApplied': 'Successfully Applied!',
  'applicationFailed': 'Application failed, please try again',
  'applicationSuccessMessage':
      'Your application has been submitted successfully!',
  'mustAddCVBeforeApplying': 'Please add a CV to your profile before applying',

  // Apply Job - Additional
  'cancelButton': 'Cancel',
  'readyToApplyStatus': 'Ready to apply',
  'optionalLabel': 'Optional',
  'goToProfile': 'Go to Profile',
  'coverLetterPlaceholder':
      'Introduce yourself to the hiring manager. Highlight your relevant skills and why you\'re a great fit for this role...',
  'reviewSelectedCvTitle': 'Review Selected CV',
  'attachedToApplicationStatus': 'Attached to application',
  'changeCvButton': 'Change CV',
  'submitApplicationButton': 'Submit Application',
  'submittingButton': 'Submitting...',
  'termsAgreement': 'By submitting, you agree to our',
  'applicationSentSuccess': 'Application Sent\nSuccessfully!',
  'applicationReceivedMessage': 'Your application for ',
  'atLabel': ' at ',
  'hasBeenReceived': ' has been received.',
  'viewApplicationStatusButton': 'View Application Status',
  'backToHomeButton': 'Back to Home',
  'nextButton': 'Next',

  // Home Page
  'homePageTitle': 'Home',
  'dashboardTooltip': 'Go to Dashboard',
  'recommendedJobsTitle': 'Recommended Jobs',
  'recentJobPostingsTitle': 'Recent Job Postings',
  'searchResultsTitle': 'Search Results for',
  'noJobsFoundMessage': 'No jobs found',
  'loadMoreButton': 'Load More',

  // Interview Schedule
  'interviewScheduleTitle': 'Interview Schedule',
  'noInterviewsMessage': 'No interview schedules yet',
  'statusAccepted': 'Accepted',
  'statusRejected': 'Rejected',
  'statusReschedule': 'Reschedule Request',
  'statusPending': 'Pending',
  'declineButton': 'Decline',
  'rescheduleButton': 'Reschedule',
  'acceptButton': 'Accept',
  'scheduleConfirmedMessage': 'Schedule confirmed!',
  'scheduleDeclinedMessage': 'Schedule declined',
  'rescheduleRequestedMessage': 'Reschedule requested',
  'contactLabel': 'Contact:',
  'noLocationText': 'No location',
  'notAvailable': 'N/A',

  // Applications Page
  'applicationHistoryTitle': 'Application History',
  'appliedTabLabel': 'Applied',
  'interviewsTabLabel': 'Interviews',
  'acceptedTabLabel': 'Accepted',
  'couldNotLoadProfileMessage': 'Could not load profile',
  'retryButton': 'Retry',
  'noApplicationsFoundMessage': 'No applications found',
  'noApplicationsFoundDescription':
      'Your applications for this category will appear here',
  'appliedOnLabel': 'Applied on',
  'withdrawButton': 'Withdraw',
  'withdrawConfirmTitle': 'Withdraw application?',
  'withdrawConfirmMessage':
      'Are you sure you want to withdraw this application?',
  'withdrawSuccessMessage': 'Application withdrawn successfully',
  'withdrawFailureMessage': 'Failed to withdraw application',

  // Messages Page
  'messagesPageTitle': 'Messages',
  'fromEmployersSubtitle': 'From employers',
  'messageSearchPlaceholder': 'Search messages, companies...',
  'unreadFilterLabel': 'Unread',
  'urgentHiringFilterLabel': 'Urgent Hiring',
  'interviewedFilterLabel': 'Interviewed',
  'savedFilterLabel': 'Saved',
  'pinnedSectionLabel': 'Pinned',
  'allSectionLabel': 'All',
  'respondWithin24hTag': 'Respond within 24h',
  'pinnedTag': 'Pinned',

  // Welcome Page
  'welcomeTitle': 'Find Your Dream Job',
  'welcomeDescription':
      'Explore thousands of job opportunities\nand start your career journey today',

  // Forgot Password
  'checkEmailTitle': 'Check your email',
  'otpSentMessage': 'We sent a 6-digit OTP to',
  'enterOtpPlaceholder': 'Enter OTP',
  'verifyOtpButton': 'Verify OTP',
  'insufficientOtpError': 'Please enter all 6 digits of OTP',
  'invalidOtpError': 'Invalid OTP',
  'expiredOtpError': 'OTP invalid or expired',
  'otpResendMessage': 'Didn\'t receive the code?',
  'resendButton': 'Resend',
  'otpResentSuccess': 'OTP has been resent',
  'resendFailure': 'Resend failed:',
  'employerDashboard': 'Dashboard',
  'overview': 'Overview',
  'last30Days': 'Last 30 days',
  'activeJobs': 'Active Jobs',
  'applicants': 'Applicants',
  'interviewsCount': 'Interviews',
  'recentActivities': 'Recent Activities',
  'viewAll': 'View all',
  'manageJobs': 'Manage Jobs',
  'noJobsYet': 'No jobs yet',
  'createFirstJobPost':
      'Create your first job post to start receiving applicants.',
  'postNewJob': 'Post New Job',
  'draftJobs': 'Draft Jobs',
  'closedJobs': 'Closed Jobs',
  'reopenJobTitle': 'Reopen job?',
  'reopenJobConfirm': 'Reopen this job?',
  'deleteJobTitle': 'Delete job?',
  'deleteJobConfirm': 'Delete this job?',
  'jobReopenedSuccess': 'Job reopened successfully.',
  'jobDeleted': 'Job deleted.',
  'noJobsInTab': 'No jobs in this tab yet',
  'tryCreatingNewJob': 'Try creating a new job post or switch to another tab.',
  'boostFeatureComingSoon': 'Boost feature coming soon.',
  'editJob': 'Edit Job',
  'postANewJob': 'Post a New Job',
  'saveDraft': 'Save Draft',
  'previewJob': 'Preview Job',
  'nextStep': 'Next Step',
  'jobTitleRequired': 'Job title is required',
  'pleaseChooseCategory': 'Please choose a category',
  'locationRequired': 'Location is required',
  'descriptionRequired': 'Job description is required',
  'requirementsRequired': 'Job requirements are required',
  'employmentTypeRequired': 'Employment type is required',
  'positionsGreaterThanZero': 'Open positions must be greater than 0',
  'chooseDeadline': 'Please choose an application deadline',
  'addSalaryRange':
      'Please add a salary range or mark the salary as negotiable',
  'jobTitleDraftRequired': 'Job title is required to save a draft',
  'jobUpdatedSuccess': 'Job updated successfully!',
  'jobPostedSuccess': 'Job posted successfully!',
  'draftSavedSuccess': 'Draft saved successfully!',
  'example': 'e.g.',
  'selectCategory': 'Select Category',
  'negotiable': 'Negotiable',
  'openPositions': 'Open Positions',
  'applicationDeadline': 'Application Deadline',
  'selectDate': 'Select Date',
  'perksAndBenefits': 'Perks & Benefits',
  'salaryRange': 'Salary Range',
  'minSalary': 'Min Salary',
  'maxSalary': 'Max Salary',
  'perMonth': 'Per Month',
  'jobDescription': 'Job Description',
  'jobRequirements': 'Job Requirements',
  'skillsAndTags': 'Skills & Tags',
  'addSkillHint': 'Add a skill and press Enter',
  'employmentType': 'Employment Type',
  'fullTime': 'Full-time',
  'partTime': 'Part-time',
  'contract': 'Contract',
  'freelance': 'Freelance',
  'internship': 'Internship',
  'remote': 'Remote',
  'experienceLevel': 'Experience Level',
  'entryLevel': 'Entry',
  'midLevel': 'Mid',
  'seniorLevel': 'Senior',
  'leadLevel': 'Lead',
  'clearAll': 'Clear All',
  'showResults': 'Show Results',
  'enterLocationHint': 'Enter city, state or country',
  'jobSaved': 'Job Saved!',
  'addedToFavorites': 'Added to your\nfavorite list',
  'applicantsSoFar': 'applicants so far',
  'resumePreview': 'Resume Preview',
  'filesCount': 'FILES',
  'replacedSuccess': 'Replaced successfully',
  'couldNotOpenUrl': 'Could not open the CV URL',
  'uploadedLabel': 'Uploaded',
  'applicationTimeline': 'Application Timeline',
  'applicationSubmitted': 'Application Submitted',
  'underReview': 'Under Review',
  'shortlistedInterview': 'Shortlisted/Interview',
  'decision': 'Decision',
  'yourApplication': 'Your Application',
  'attachedResume': 'Attached Resume',
  'withdrawConfirmMessageUndo':
      'Are you sure you want to withdraw? You cannot undo this action.',
  'pendingReview': 'Pending Review',
  'employerReviewing': 'Employer Reviewing',
  'interviewInvited': 'Interview Invited',
  'acceptedHired': 'Accepted / Hired',
  'notSelected': 'Not Selected',
  'withdrawnByYou': 'Withdrawn by You',
  'currentStatus': 'Current Status',
  'applicationStatus': 'Application Status',
  'negotiableSubtitle': 'Let candidates know salary can be discussed.',
};
