final Map<String, String> englishStrings = {
  // Auth
  'email': 'Email',
  'password': 'Password',
  'confirmPassword': 'Confirm Password',
  'login': 'Login',
  'register': 'Register',
  'logout': 'Logout',
  'forgotPassword': 'Forgot Password?',
  'resetPassword': 'Reset Password',
  'signUp': 'Sign Up',
  'signIn': 'Sign In',
  'signInWithGoogle': 'Sign In with Google',
  'signInWithFacebook': 'Sign In with Facebook',
  'alreadyHaveAccount': 'Already have an account?',
  'dontHaveAccount': 'Don\'t have an account?',
  'invalidEmail': 'Please enter a valid email',
  'passwordTooShort': 'Password must be at least 6 characters',
  'passwordsDoNotMatch': 'Passwords do not match',
  'emailAlreadyExists': 'Email already exists',
  'invalidCredentials': 'Invalid email or password',
  'loginSuccess': 'Login successful',
  'registerSuccess': 'Registration successful',
  'logoutSuccess': 'Logout successful',
  'emailAddressHint': 'Email Address',
  'passwordHint': 'Password',
  'rememberMe': 'Remember me',
  'welcomeBack': 'Welcome Back',
  'signInToContinue': 'Sign in to continue your job search',
  'dontHaveAccountQuestion': 'Don\'t have an account?',
  'loginError': 'Login failed',
  'emailRequired': 'Email is required',
  'invalidEmailFormat': 'Invalid email format',
  'invalidPhoneFormat': 'Invalid phone number format',
  'invalidWebsiteFormat': 'Invalid website format',
  'passwordRequired': 'Password is required',

  // Profile
  'profile': 'Profile',
  'editProfile': 'Edit Profile',
  'fullName': 'Full Name',
  'phoneNumber': 'Phone Number',
  'address': 'Address',
  'bio': 'Bio',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'close': 'Close',
  'edit': 'Edit',
  'info': 'Info',
  'favorites': 'Favorites',
  'profileUpdated': 'Profile updated successfully',
  'messagesTitle': 'Messages',
  'fromRecruiters': 'From recruiters',
  'searchMessagesHint': 'Search messages, companies...',
  'unreadFilter': 'Unread',
  'urgentFilter': 'Urgent',
  'interviewedFilter': 'Interviewed',
  'savedFilter': 'Saved',
  'pinnedLabel': 'Pinned',
  'allLabel': 'All',
  'respondsIn24h': 'Responds in 24h',
  'resume': 'Resume',
  'uploadResume': 'Upload Resume',
  'replaceResume': 'Replace Resume',
  'deleteResume': 'Delete Resume',
  'viewResume': 'View Resume',
  'skills': 'Skills',
  'experience': 'Experience',
  'education': 'Education',
  'resumeDocuments': 'Resume & Documents',
  'resumeFiles': 'FILES',
  'browseFiles': 'Browse Files',
  'uploadThankYou': 'Upload successful',
  'uploadFailed': 'Upload failed',
  'replaceFailed': 'Replace failed',
  'deleteSuccess': 'Delete successful',
  'setDefaultSuccess': 'Set as default successful',
  'replaceSuccess': 'Replaced successfully',

  // Jobs
  'jobs': 'Jobs',
  'jobTitle': 'Job Title',
  'company': 'Company',
  'location': 'Location',
  'salary': 'Salary',
  'description': 'Description',
  'requirements': 'Requirements',
  'applyJob': 'Apply for Job',
  'appliedJobs': 'Applied Jobs',
  'savedJobs': 'Saved Jobs',
  'jobDetails': 'Job Details',
  'noJobsFound': 'No jobs found',
  'applySuccess': 'Application submitted successfully',
  'apply': 'Apply',
  'favoriteJobs': 'Favorite Jobs',

  // Common
  'home': 'Home',
  'search': 'Search',
  'settings': 'Settings',
  'language': 'Language',
  'selectLanguage': 'Select language',
  'notifications': 'Notifications',
  'help': 'Help',
  'about': 'About',
  'version': 'Version',
  'loading': 'Loading...',
  'error': 'Error',
  'errorMessage': 'Error: ',
  'success': 'Success',
  'tryAgain': 'Try Again',
  'noInternetConnection': 'No Internet Connection',
  'somethingWentWrong': 'Something went wrong',
  'open': 'Open',
  'yes': 'Yes',
  'no': 'No',
  'ok': 'OK',
  'contactUs': 'Contact Us',
  'privacyPolicy': 'Privacy Policy',
  'termsOfService': 'Terms of Service',
  'helpCenter': 'Help Center',
  'privacyPolicyContent':
      'Privacy Policy\n\n'
      '1) Data we collect\n'
      '- Profile, contact, and in-app activity information.\n'
      '- Basic usage logs to improve the experience.\n\n'
      '2) Purpose of use\n'
      '- Connect employers with candidates.\n'
      '- Send recruitment-related notifications.\n'
      '- Support customer care and account security.\n\n'
      '3) Data protection\n'
      '- Data is stored securely and accessed only when necessary.\n'
      '- You can request updates or deletion of your information.\n\n'
      '4) Data sharing\n'
      '- Shared only within recruitment features.\n'
      '- We do not sell data to third parties.',
  'termsOfServiceContent':
      'Terms of Service\n\n'
      '1) Account\n'
      '- Provide accurate and up-to-date information.\n'
      '- You are responsible for keeping your account secure.\n\n'
      '2) Content\n'
      '- Do not post illegal or misleading content.\n'
      '- Employers are responsible for job posting accuracy.\n\n'
      '3) Prohibited behavior\n'
      '- Fraud, spam, or unauthorized system access.\n'
      '- Attacking or disrupting the service.\n\n'
      '4) Changes to terms\n'
      '- Terms may be updated and announced in-app.',
  'helpCenterContent':
      'Help Center\n\n'
      'We can assist with:\n'
      '- Missing notifications.\n'
      '- Login issues or email verification.\n'
      '- Profile updates, job posts, and applications.\n\n'
      'Quick self-help tips:\n'
      '1) Check your network connection.\n'
      '2) Update the app to the latest version.\n'
      '3) Sign out and sign back in.\n\n'
      'If the issue persists, contact us.',
  'contactUsContent':
      'Contact Us\n\n'
      'Email: support@jobgo.vn\n'
      'Hotline: 1900 123 456 (08:30 - 18:00)\n'
      'Address: 68 Nguyen Hue, District 1, Ho Chi Minh City\n\n'
      'We respond within 24 - 48 business hours.',
  'changePassword': 'Change Password',
  'pushNotifications': 'Push Notifications',
  'account': 'ACCOUNT',
  'privacy': 'PRIVACY',
  'support': 'SUPPORT',
  'desiredPosition': 'Desired Position',
  'yearsOfExperience': 'Years of Experience',
  'positionDesiredTitle': 'Position Desired: ',
  'exitApplication': 'Exit Application',
  'coverLetter': 'Cover Letter',
  'applySuccessMessage': 'Application submitted successfully',
  'stepOfThree': 'STEP 1 OF 3',
  'chooseYourRole': 'Choose your role',
  'selectHowToUse': 'Select how you want to use the platform',
  'iAmCandidate': 'I am a Candidate',
  'candidateDescription':
      'I\'m looking for new career opportunities and want to showcase my talent.',
  'iAmEmployer': 'I am an Employer',
  'employerDescription':
      'I\'m looking to hire talented candidates for my company.',
  'next': 'Next',
  'back': 'Back',
  'selectRole': 'Please select a role to continue',
  'uploadNewResume': 'Upload a new resume',
  'uploadFileSize': 'PDF, DOCX, TXT up to 10MB',
  // Register Info Page
  'fullNameHint': 'Full Name',
  'fullNameRequired': 'Full name is required',
  'fullNameLength': 'Full name must be at least 2 characters',
  'emailAddressRequired': 'Email is required',
  'passwordMinLength': 'Password must be at least 6 characters',
  'confirmPasswordLabel': 'Confirm Password',
  'confirmPasswordHint': 'Confirm Password',
  'passwordMismatch': 'Passwords do not match',
  // Register Verify Email
  'stepOfThreeMsg': 'STEP 3 OF 3',
  'otpVerification': 'OTP Verification',
  'emailVerificationMessage': 'We sent a confirmation link to',
  'clickLinkMessage': 'Click the link in your email to activate your account.',
  'confirmedEmail': "I've confirmed my email",
  'didNotReceiveEmail': "Didn't receive the email?",
  'resendEmail': 'Resend email',
  'requestNewCode': 'Request new code in',
  'verificationSuccess': 'Email verified successfully!',
  'verificationFailed': 'Email verification failed',
  'resendFailed': 'Failed to resend email',

  // Job Search & Details
  'searchJobTitle': 'Search job title or keyword',
  'clearFilters': 'Clear filters',
  'noJobsMatch': 'No jobs match your filters.',
  'jobsFound': 'jobs found',
  'filters': 'Filters',
  'mostRelevant': 'Most Relevant',
  'alreadyApplied': 'Already Applied',
  'applyNow': 'Apply Now',
  'jobClosed': 'Job Closed',

  // Apply Job
  'applyForJob': 'Apply for Job',
  'selectCV': 'Select CV',
  'chooseResumeForApplication':
      'Choose the resume you\'d like to use for this application.',
  'noCVFound': 'No CV found in your profile',
  'pleaseUploadCVBeforeApplying':
      'Please upload a CV to your profile before applying.',
  'resumeSelection': 'Resume Selection',
  'finalReview': 'FINAL REVIEW',
  'step1Of2': 'STEP 1 OF 2',
  'step2Of2': 'Step 2 of 2',
  'successfullyApplied': 'Successfully Applied!',
  'applicationFailed': 'Application failed, please try again',
  'applicationSuccessMessage':
      'Your application has been submitted successfully!',
  'mustAddCVBeforeApplying': 'Please add a CV to your profile before applying',

  // Apply Job - Additional
  'aiCvFit': 'AI CV Fit',
  'aiInsight': 'AI Insight',
  'aiMatch': 'AI Match',
  'analyze': 'Analyze',
  'analyzeCv': 'Analyze CV',
  'reanalyze': 'Re-analyze',
  'aiAnalysisSupportsPdfOnly': 'AI analysis supports PDF, DOCX, and TXT only.',
  'missingJobDetailsForAiAnalysis': 'Missing job details for AI analysis.',
  'noAiAnalysisYet':
      'No AI analysis yet. Run analysis to get fit score and interview insights.',
  'missingSkillsLabel': 'Missing skills:',
  'interviewChecksLabel': 'Interview checks:',
  'suggestionsLabel': 'Suggestions:',
  'coverLetterTipsLabel': 'Cover letter tips:',
  'analyzeFailed': 'Analyze failed',
  'invalidJobIdentifier': 'Invalid job identifier.',
  'refreshFailed': 'Refresh failed',
  'viewProfile': 'View Profile',
  'message': 'Message',
  'chooseProfileImage': 'Choose profile image',
  'takeNewPhoto': 'Take new photo',
  'chooseFromLibrary': 'Choose from library',
  'cancelButton': 'Cancel',
  'readyToApplyStatus': 'Ready to apply',
  'optionalLabel': 'Optional',
  'goToProfile': 'Go to Profile',
  'coverLetterPlaceholder':
      'Introduce yourself to the hiring manager. Highlight your relevant skills and why you\'re a great fit for this role...',
  'reviewSelectedCvTitle': 'Review Selected CV',
  'attachedToApplicationStatus': 'Attached to application',
  'changeCvButton': 'Change CV',
  'submitApplicationButton': 'Submit Application',
  'submittingButton': 'Submitting...',
  'termsAgreement': 'By submitting, you agree to our',
  'applicationSentSuccess': 'Application Sent\nSuccessfully!',
  'applicationReceivedMessage': 'Your application for ',
  'atLabel': ' at ',
  'hasBeenReceived': ' has been received.',
  'viewApplicationStatusButton': 'View Application Status',
  'backToHomeButton': 'Back to Home',
  'nextButton': 'Next',

  // Home Page
  'homePageTitle': 'Home',
  'dashboardTooltip': 'Go to Dashboard',
  'recommendedJobsTitle': 'Recommended Jobs',
  'recentJobPostingsTitle': 'Recent Job Postings',
  'searchResultsTitle': 'Search Results for',
  'noJobsFoundMessage': 'No jobs found',
  'loadMoreButton': 'Load More',

  // Interview Schedule
  'interviewScheduleTitle': 'Interview Schedule',
  'noInterviewsMessage': 'No interview schedules yet',
  'statusAccepted': 'Accepted',
  'statusRejected': 'Rejected',
  'statusReschedule': 'Reschedule Request',
  'statusPending': 'Pending',
  'declineButton': 'Decline',
  'rescheduleButton': 'Reschedule',
  'acceptButton': 'Accept',
  'scheduleConfirmedMessage': 'Schedule confirmed!',
  'scheduleDeclinedMessage': 'Schedule declined',
  'rescheduleRequestedMessage': 'Reschedule requested',
  'noLocationText': 'No location',
  'notAvailable': 'N/A',

  // Applications Page
  'applicationHistoryTitle': 'Application History',
  'appliedTabLabel': 'Applied',
  'interviewsTabLabel': 'Interviews',
  'acceptedTabLabel': 'Accepted',
  'couldNotLoadProfileMessage': 'Could not load profile',
  'retryButton': 'Retry',
  'noApplicationsFoundMessage': 'No applications found',
  'noApplicationsFoundDescription':
      'Your applications for this category will appear here',
  'appliedOnLabel': 'Applied on',
  'withdrawButton': 'Withdraw',
  'withdrawConfirmTitle': 'Withdraw application?',
  'withdrawConfirmMessage':
      'Are you sure you want to withdraw this application?',
  'withdrawSuccessMessage': 'Application withdrawn successfully',
  'withdrawFailureMessage': 'Failed to withdraw application',

  // Messages Page
  'messagesPageTitle': 'Messages',
  'fromEmployersSubtitle': 'From employers',
  'messageSearchPlaceholder': 'Search messages, companies...',
  'unreadFilterLabel': 'Unread',
  'urgentHiringFilterLabel': 'Urgent Hiring',
  'interviewedFilterLabel': 'Interviewed',
  'savedFilterLabel': 'Saved',
  'pinnedSectionLabel': 'Pinned',
  'allSectionLabel': 'All',
  'respondWithin24hTag': 'Respond within 24h',
  'pinnedTag': 'Pinned',

  // Welcome Page
  'welcomeTitle': 'Find Your Dream Job',
  'welcomeDescription':
      'Explore thousands of job opportunities\nand start your career journey today',

  // Forgot Password
  'checkEmailTitle': 'Check your email',
  'otpSentMessage': 'We sent a 6-digit OTP to',
  'enterOtpPlaceholder': 'Enter OTP',
  'verifyOtpButton': 'Verify OTP',
  'insufficientOtpError': 'Please enter all 6 digits of OTP',
  'invalidOtpError': 'Invalid OTP',
  'expiredOtpError': 'OTP invalid or expired',
  'otpResendMessage': 'Didn\'t receive the code?',
  'resendButton': 'Resend',
  'otpResentSuccess': 'OTP has been resent',
  'resendFailure': 'Resend failed:',
  'employerDashboard': 'Dashboard',
  'overview': 'Overview',
  'last30Days': 'Last 30 days',
  'activeJobs': 'Active Jobs',
  'applicants': 'Applicants',
  'interviewsCount': 'Interviews',
  'recentActivities': 'Recent Activities',
  'viewAll': 'View all',
  'manageJobs': 'Manage Jobs',
  'noJobsYet': 'No jobs yet',
  'createFirstJobPost':
      'Create your first job post to start receiving applicants.',
  'postNewJob': 'Post New Job',
  'needToHire': 'Need to hire?',
  'postNewJobDescription': 'Post a new job opportunity today',
  'draftJobs': 'Draft Jobs',
  'closedJobs': 'Closed Jobs',
  'allJobs': 'All Jobs',
  'activeStatus': 'ACTIVE',
  'closedStatus': 'CLOSED',
  'draftStatus': 'DRAFT',
  'pendingStatus': 'Pending',
  'untitledJob': 'Untitled Job',
  'viewApplicants': 'View Applicants →',
  'viewHistory': 'View History →',
  'reopen': 'Reopen',
  'reopenJobTitle': 'Reopen job?',
  'reopenJobConfirm': 'Reopen this job?',
  'deleteJobTitle': 'Delete job?',
  'deleteJobConfirm': 'Delete this job?',
  'closeJobTitle': 'Close job?',
  'closeJobConfirm': 'Close this job? You can reopen it later.',
  'jobReopenedSuccess': 'Job reopened successfully.',
  'jobDeleted': 'Job deleted.',
  'jobClosedSuccess': 'Job closed.',
  'noJobsInTab': 'No jobs in this tab yet',
  'tryCreatingNewJob': 'Try creating a new job post or switch to another tab.',
  'boostFeatureComingSoon': 'Boost feature coming soon.',
  'couldNotLoadJobs': 'Could not load jobs.',
  'editJob': 'Edit Job',
  'postANewJob': 'Post a New Job',
  'reviewJobChanges': 'Review Job Changes',
  'previewJobPost': 'Preview Job Post',
  'confirmAndPost': 'Confirm & Post',
  'publishJob': 'Publish Job',
  'updateJob': 'Update Job',
  'backToEdit': 'Back to Edit',
  'addAnotherJob': 'Add Another Job',
  'saveDraft': 'Save Draft',
  'previewJob': 'Preview Job',
  'nextStep': 'Next Step',
  'jobTitleRequired': 'Job title is required',
  'pleaseChooseCategory': 'Please choose a category',
  'locationRequired': 'Location is required',
  'descriptionRequired': 'Job description is required',
  'requirementsRequired': 'Job requirements are required',
  'chooseAtLeastOneSkill': 'Please choose at least one skill',
  'employmentTypeRequired': 'Employment type is required',
  'positionsGreaterThanZero': 'Open positions must be greater than 0',
  'positionsMustBeWholeNumber': 'Open positions must be a whole number',
  'positionsTooLarge': 'Open positions cannot exceed 1000',
  'chooseDeadline': 'Please choose an application deadline',
  'deadlineCannotBePast': 'Application deadline cannot be in the past',
  'addSalaryRange': 'Please add a salary range',
  'chooseAtLeastOneBenefit': 'Please choose at least one benefit',
  'salaryInvalidNumber': 'Salary must be a valid number',
  'salaryMustBePositive': 'Salary must be greater than 0',
  'salaryMinGreaterThanMax':
      'Minimum salary cannot be greater than maximum salary',
  'jobTitleDraftRequired': 'Job title is required to save a draft',
  'jobTitleTooLong': 'Job title cannot exceed 120 characters',
  'locationTooLong': 'Location cannot exceed 120 characters',
  'jobUpdatedSuccess': 'Job updated successfully!',
  'jobPostedSuccess': 'Job posted successfully!',
  'draftSavedSuccess': 'Draft saved successfully!',
  'example': 'e.g.',
  'selectCategory': 'Select Category',
  'jobTitleExampleHint': 'e.g. Senior Flutter Developer',
  'experienceExampleHint': 'e.g. 5+ years experience...',
  'softwareDevelopment': 'Software Development',
  'designCreative': 'Design & Creative',
  'productManagement': 'Product Management',
  'dataScienceAnalytics': 'Data Science & Analytics',
  'devOpsInfrastructure': 'DevOps & Infrastructure',
  'marketingGrowth': 'Marketing & Growth',
  'salesBusinessDevelopment': 'Sales & Business Development',
  'humanResources': 'Human Resources',
  'financeAccounting': 'Finance & Accounting',
  'operationsAdministration': 'Operations & Administration',
  'negotiable': 'Negotiable',
  'openPositions': 'Open Positions',
  'opening': 'opening',
  'openings': 'openings',
  'applicationDeadline': 'Application Deadline',
  'selectDate': 'Select Date',
  'perksAndBenefits': 'Perks & Benefits',
  'noBenefitsAddedYet': 'No benefits added yet.',
  'includedBenefit': 'Included benefit',
  'salaryRange': 'Salary Range',
  'minSalary': 'Min Salary',
  'maxSalary': 'Max Salary',
  'fromSalary': 'From',
  'upToSalary': 'Up to',
  'perMonth': 'Per Month',
  'jobDescription': 'Job Description',
  'jobRequirements': 'Job Requirements',
  'noDescriptionProvidedYet': 'No description provided yet.',
  'noRequirementsListedYet': 'No requirements listed yet.',
  'skillsAndTags': 'Skills & Tags',
  'addSkillHint': 'Add a skill and press Enter',
  'employmentType': 'Employment Type',
  'fullTime': 'Full-time',
  'partTime': 'Part-time',
  'contract': 'Contract',
  'freelance': 'Freelance',
  'internship': 'Internship',
  'remote': 'Remote',
  'addSkills': 'Add Skills',
  'addCustom': '+ Add Custom',
  'customSkillComingSoon': 'Custom skill coming soon',
  'customSkillDialogTitle': 'Add Custom Skill',
  'customSkillDescriptionHint': 'Short description (optional)',
  'customSkillSaveAction': 'Save Skill',
  'customSkillNameRequired': 'Please enter a skill name',
  'customSkillNameTooShort': 'Skill name must be at least 2 characters',
  'customSkillNameTooLong': 'Skill name cannot exceed 50 characters',
  'customSkillNameInvalid':
      'Skill name may include letters, numbers and + # . - / &',
  'customSkillAlreadyExists': 'This skill already exists',
  'customSkillAlreadySelected': 'This skill is already selected',
  'customSkillAddedSuccess': 'Skill added successfully',
  'customSkillAddedLocalOnly':
      'Skill was added to this job, but could not be saved to shared catalog.',
  'customSkillCatalogFallback':
      'Could not load system skill catalog, using suggested list.',
  'figma': 'Figma',
  'uiDesign': 'UI Design',
  'flutter': 'Flutter',
  'react': 'React',
  'communication': 'Communication',
  'leadership': 'Leadership',
  'healthInsurance': 'Health Insurance',
  'gym': 'Gym',
  'bonus': 'Bonus',
  'remoteWork': 'Remote Work',
  'paidLeave': 'Paid Leave',
  'flexibleHours': 'Flexible Hours',
  'stockOptions': 'Stock Options',
  'unknownCompany': 'Unknown Company',
  'locationNotSet': 'Location not set',
  'verified': 'Verified',
  'readyToPublish': 'Ready to publish',
  'missing': 'Missing',
  'statusDraft': 'DRAFT',
  'statusClosed': 'CLOSED',
  'statusActive': 'ACTIVE',
  'couldNotSaveJob': 'Could not save the job post.',
  'experienceLevel': 'Experience Level',
  'entryLevel': 'Entry',
  'midLevel': 'Mid',
  'seniorLevel': 'Senior',
  'leadLevel': 'Lead',
  'clearAll': 'Clear All',
  'showResults': 'Show Results',
  'enterLocationHint': 'Enter city, state or country',
  'jobSaved': 'Job Saved!',
  'addedToFavorites': 'Added to your\nfavorite list',
  'applicantsSoFar': 'applicants so far',
  'resumePreview': 'Resume Preview',
  'filesCount': 'FILES',
  'replacedSuccess': 'Replaced successfully',
  'couldNotOpenUrl': 'Could not open the CV URL',
  'uploadedLabel': 'Uploaded',
  'applicationTimeline': 'Application Timeline',
  'applicationSubmitted': 'Application Submitted',
  'underReview': 'Under Review',
  'shortlistedInterview': 'Shortlisted/Interview',
  'decision': 'Decision',
  'yourApplication': 'Your Application',
  'attachedResume': 'Attached Resume',
  'withdrawConfirmMessageUndo':
      'Are you sure you want to withdraw? You cannot undo this action.',
  'pendingReview': 'Pending Review',
  'employerReviewing': 'Employer Reviewing',
  'interviewInvited': 'Interview Invited',
  'acceptedHired': 'Accepted / Hired',
  'notSelected': 'Not Selected',
  'withdrawnByYou': 'Withdrawn by You',
  'currentStatus': 'Current Status',
  'applicationStatus': 'Application Status',
  'negotiableSubtitle': 'Let candidates know salary can be discussed.',

  // Deleted Users
  'restoreAccountTitle': 'Restore Account',
  'restoreAccountConfirm': 'Do you want to restore account',
  'restoreAccountNormal': 'This account will operate normally again.',
  'restoreAction': 'Restore',
  'restoreSuccess': 'Account restored successfully.',
  'restoreError': 'Error restoring account.',
  'hardDeleteTitle': 'PERMANENT DELETE',
  'hardDeleteConfirm': 'WARNING: This action will permanently delete',
  'hardDeleteUndone':
      'from the Supabase database and cannot be undone. Are you sure?',
  'hardDeleteAction': 'Delete permanently',
  'hardDeleteSuccess': 'Permanently deleted from the system.',
  'hardDeleteError': 'Error deleting permanently.',
  'accountTrashTitle': 'Account Trash',
  'emptyTrash': 'Trash is empty',
  'rolePrefix': 'Role:',

  // Employer detail & popup
  'employerDetail': 'Employer Details',
  'companySize': 'Company Size',
  'industryLabel': 'Industry',
  'contactInfo': 'Contact Information',
  'copyAddressSuccess': 'Address copied to clipboard!',
  'chatWithEmployer': 'Chat with Employer',
  'noDescriptionProvided': 'No detailed description provided by the employer.',
  'phoneLabel': 'Phone',
  'emailLabel': 'Email',
  'websiteLabel': 'Website',
  'addressLabel': 'Address',
  'noPhone': 'No phone number',
  'noEmail': 'No email',
  'noWebsite': 'No website',
  'noAddress': 'No address',
  'recruiter': 'Recruiter',
  'viewDetails': 'Details',
  'messageNow': 'Message Now',
  'employerLabel': 'Employer',
  'activeNow': 'Active now',
  'employerAccountNotFound': 'Could not find this employer\'s account.',
  'emailSubjectQuery': 'Inquiry about job position',
  'featureInDevelopment':
      'This feature is currently under development. Please check back later!',
  'featureInDevelopmentTitle': 'Coming Soon',
  //kinh nghiệm - kĩ năng
  'addExperience': 'Add Experience',
  'companyName': 'Company Name',
  'companyNameHint': 'e.g. Google',
  'position': 'Position',
  'positionHint': 'e.g. Flutter Developer',
  'startDate': 'Start Date',
  'endDate': 'End Date',
  'endDateHint': 'Leave empty if current job',
  'describeRole': 'Describe your role...',
  'fillRequiredFields': 'Please fill in all required fields',
  'endDateBeforeStart': 'End date must be after start date',
  'workExperience': 'Work Experience',
  'noExperienceYet': 'No experience added yet.\nTap Add to get started.',
  'deleteExperience': 'Delete Experience',
  'deleteExperienceConfirm': 'Are you sure you want to delete this experience?',
  'add': 'Add',
  'skillLabel': 'Skill',
  'skillSearchHint': 'Type to search skill...',
  'responsesTabLabel': 'Responses',
  'systemTabLabel': 'System',
  'reportsTabLabel': 'Reports',
  'noNotificationsMessage': 'No notifications yet',
  'unableToLoadNotifications': 'Unable to load notifications',
  'markAllAsRead': 'Mark all as read',
  'allMarkedAsReadMessage': 'All notifications marked as read',

  // Employer Dashboard / Profile / Edit Profile
  'companyManagement': 'COMPANY MANAGEMENT',
  'billingAndSecurity': 'BILLING & SECURITY',
  'companyProfile': 'Company Profile',
  'viewPublicCompanyPage': 'View public company page',
  'companyInformation': 'Company Information',
  'logoBannerDescription': 'Logo, banner, and description',
  'teamManagement': 'Team Management',
  'manageRecruitersPermissions': 'Manage recruiters and permissions',
  'billingSubscription': 'Billing & Subscription',
  'managePlansInvoices': 'Manage plans and invoices',
  'accountSecurity': 'Account Security',
  'password2faActivity': 'Password, 2FA, login activity',
  'helpCenterDesc': 'Documentation and live chat',
  'contactUsDesc': 'Get in touch with support',
  'verifiedEmployer': 'Verified Employer',
  'saveChanges': 'Save Changes',
  'logoUploadSuccess': 'Logo uploaded successfully!',
  'logoUploadFailed': 'Failed to upload logo. Please try again.',
  'profileUpdateSuccess': 'Company profile updated successfully!',
  'profileUpdateFailed': 'Failed to update profile. Please try again.',
  'isFieldsRequired': 'is required',
  'goodMorning': 'Good Morning',
  'goodAfternoon': 'Good Afternoon',
  'goodEvening': 'Good Evening',
  'employerDashboardTitle': 'Employer Dashboard',
  'activeLabel': 'Active',
  'newProfiles': 'New Profiles',
  'viewsStatistics': 'Views Statistics',
  'totalReachThisWeek': 'Total reach this week',
  'totalViews': 'Total Views',
  'companyIntro': 'Introduction',
  'noCompanyData': 'No company data',
  'couldNotLoadCompanyProfile': 'Could not load company profile',
  'companyDetail': 'Company details',
  'unnamedCompany': 'Unnamed company',
  'noCompanyDescription': 'No description yet',
  'noCompanyAddress': 'No address yet',
  'noCompanyWebsite': 'No website yet',
  'noCompanyEmail': 'No email yet',
  'noCompanyPhone': 'No phone number yet',
  'noCompanySize': 'No company size yet',
  'deleteCompanyProfileTitle': 'Confirm delete',
  'deleteCompanyProfileConfirm':
      'Are you sure you want to delete this company profile?',
  'companyProfileDeleted': 'Company profile deleted',
  'deleteErrorPrefix': 'Delete failed: ',

  // Employer Messages
  'allMessagesSection': 'All Messages',
  'chatWithCandidatesPartners': 'Chat with candidates & partners',
  'noMessagesDescription': 'No messages yet',
  'unableToLoadMessages': 'Unable to load messages',

  // Employer Applicants / Candidate Profile
  'profileSummary': 'Profile Summary',
  'candidateProfileTitle': 'Candidate Profile',
  'noProfileSummary': 'No profile summary provided.',
  'seniorityLabel': 'Seniority',
  'roleLabel': 'Role',
  'educationLabel': 'Education',
  'salaryLabel': 'Salary',
  'contactLabel': 'Contact',
  'dateOfBirthLabel': 'Date of Birth',
  'notProvided': 'Not provided',
  'noExperienceProvided': 'No experience provided yet.',
  'backgroundSection': 'Background',
  'roleMatchLabel': 'Role Match',
  'genderLabel': 'Gender',
  'userIdLabel': 'User ID',
  'noSkillsProvided': 'No skills were provided for this profile yet.',
  'noResumeUploaded': 'No resume has been uploaded yet.',
  'copyResumeLink': 'Copy Resume Link',
  'resumeLinkCopied': 'Resume link copied to clipboard!',
  'shortlistSuccess': 'Candidate shortlisted successfully.',
  'shortlistFailed': 'Failed to shortlist candidate. Please try again.',
  'rejectCandidateTitle': 'Reject candidate?',
  'rejectCandidateConfirm':
      'This will mark the candidate as rejected for the current job.',
  'rejectSuccess': 'Candidate rejected successfully.',
  'rejectFailed': 'Failed to reject candidate. Please try again.',
  'noCoverLetterSubmitted':
      'No cover letter was submitted for this application.',
  'internalNotes': 'Internal Notes',
  'applicationActions': 'Application actions',
  'rejectAction': 'Reject',
  'shortlistAction': 'Shortlist',
  'scheduleAction': 'Schedule',

  // Employer Job Applicants
  'applicantsSubtitle': 'APPLICANTS',
  'searchCandidatesHint': 'Search candidates...',
  'sortLabel': 'Sort:',
  'sortNewest': 'Newest',
  'sortAiHigh': 'AI score high',
  'sortAiLow': 'AI score low',
  'invalidJobId': 'Invalid job identifier.',
  'failedToLoadApplicants': 'Failed to refresh applicants.',
  'noApplicantsFound': 'No applicants found for this job.',
  'noApplicantsMatch': 'No applicants match your search.',

  // Employer Talent Search
  'recommendedCandidates': 'RECOMMENDED CANDIDATES',
  'findTalentTitle': 'Find Talent',
  'refreshCandidatesTooltip': 'Refresh candidates',
  'searchTalentHint': 'Skills, Job Title or Name',
  'noCandidatesMatching': 'No candidates found matching your criteria.',
  'resetFilters': 'Reset filters',
  'noSkillsListed': 'No skills listed',
  'refresh': 'Refresh',
  'unableToLoadCandidates': 'Unable to load candidate list.',

  // Employer Interview Schedule / Detail / Edit / Create
  'createInterviewTitle': 'Create Interview',
  'editInterviewTitle': 'Edit Interview',
  'interviewDetailTitle': 'Interview Details',
  'createNow': 'Create now',
  'pleaseSelectJob': 'Please select job',
  'pleaseSelectCandidate': 'Please select candidate',
  'pleaseSelectDateTime': 'Please select date and time',
  'interviewDateTimeMustBeFuture':
      'Interview date and time must be in the future',
  'recruitingPosition': 'Recruiting Position *',
  'selectJobHint': 'Select job',
  'candidateRequired': 'Candidate *',
  'selectCandidateHint': 'Select candidate',
  'interviewDateLabel': 'Interview Date *',
  'selectDateHint': 'Select date',
  'interviewTimeLabel': 'Interview Time *',
  'selectTimeHint': 'Select time',
  'interviewTypeLabel': 'Type',
  'candidateInformation': 'Candidate Information',
  'appointmentInformation': 'Appointment Information',
  'candidateLabel': 'Candidate',
  'dateTimeLabel': 'Date & Time',
  'contactPersonLabel': 'Contact Person',
  'notesLabel': 'Notes',
  'notSet': 'Not set',
  'updateSchedule': 'Update Schedule',
  'locationHint': 'Enter location',
  'contactPersonHint': 'Contact person name',
  'notesHint': 'Additional notes',
  'updateInterviewSuccess': 'Interview updated successfully!',
  'deleteInterviewConfirm': 'Are you sure you want to delete this schedule?',
  'deleteInterviewTitle': 'Delete schedule',
  'deleteSuccessMsg': 'Schedule deleted successfully',
  'candidateConfirmed': 'Candidate confirmed',
  'candidateRejected': 'Candidate rejected',
  'candidateReschedule': 'Candidate requested reschedule',
  'candidatePending': 'Pending response from candidate',
  'rescheduleProposal': 'Proposed Date: ',
  'rescheduleConfirmSuccess': 'Reschedule confirmed!',
  'rescheduleRejectSuccess': 'Reschedule request declined',

  // Employer Payment
  'vnpayPaymentTitle': 'VNPay Payment',
  'paymentSuccess': 'Payment successful!',
  'paymentFailedOrCanceled': 'Payment failed or was canceled!',
  'unableToOpenPaymentBrowser': 'Unable to open browser for payment!',
  'completePaymentTitle': 'Complete payment',
  'completePaymentMessage':
      'Please complete the payment in your browser. When finished, select "Confirm paid" to continue.',
  'confirmPaid': 'Confirm paid',
  'openingPaymentBrowser': 'Opening browser for payment...',

  // Social Login Profile Completion
  'completeProfileTitle': 'Complete Your Profile',
  'completeProfileMessage':
      'Your account was created with Google. Please update your profile information (phone, address, CV...) to get the best experience.',
  'later': 'Later',

  'yearsExperienceMustBePositive':
      'Years of experience must be a number greater than 0',
  'salaryRequiredForPublish': 'Please add a salary range',
};
