final Map<String, String> vietStrings = {
  // Auth
  'email': 'Email',
  'password': 'Mật khẩu',
  'confirmPassword': 'Xác nhận mật khẩu',
  'login': 'Đăng nhập',
  'register': 'Đăng ký',
  'logout': 'Đăng xuất',
  'forgotPassword': 'Quên mật khẩu?',
  'resetPassword': 'Đặt lại mật khẩu',
  'signUp': 'Đăng ký',
  'signIn': 'Đăng nhập',
  'signInWithGoogle': 'Đăng nhập với Google',
  'signInWithFacebook': 'Đăng nhập với Facebook',
  'alreadyHaveAccount': 'Đã có tài khoản?',
  'dontHaveAccount': 'Chưa có tài khoản?',
  'invalidEmail': 'Vui lòng nhập email hợp lệ',
  'passwordTooShort': 'Mật khẩu phải có ít nhất 6 ký tự',
  'passwordsDoNotMatch': 'Mật khẩu không khớp',
  'emailAlreadyExists': 'Email đã tồn tại',
  'invalidCredentials': 'Email hoặc mật khẩu không đúng',
  'loginSuccess': 'Đăng nhập thành công',
  'registerSuccess': 'Đăng ký thành công',
  'logoutSuccess': 'Đăng xuất thành công',
  'emailAddressHint': 'Địa chỉ Email',
  'passwordHint': 'Mật khẩu',
  'rememberMe': 'Ghi nhớ tôi',
  'welcomeBack': 'Chào mừng trở lại',
  'signInToContinue': 'Đăng nhập để tiếp tục tìm kiếm việc làm của bạn',
  'dontHaveAccountQuestion': 'Chưa có tài khoản?',
  'loginError': 'Đăng nhập thất bại',
  'emailRequired': 'Email là bắt buộc',
  'invalidEmailFormat': 'Định dạng email không hợp lệ',
  'passwordRequired': 'Mật khẩu là bắt buộc',

  // Profile
  'profile': 'Hồ sơ',
  'editProfile': 'Chỉnh sửa hồ sơ',
  'fullName': 'Họ và tên',
  'phoneNumber': 'Số điện thoại',
  'address': 'Địa chỉ',
  'bio': 'Giới thiệu',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'delete': 'Xóa',
  'close': 'Đóng',
  'edit': 'Chỉnh sửa',
  'info': 'Thông tin',
  'favorites': 'Yêu thích',
  'profileUpdated': 'Hồ sơ đã được cập nhật thành công',
  'messagesTitle': 'Tin nhắn',
  'fromRecruiters': 'Từ nhà tuyển dụng',
  'searchMessagesHint': 'Tìm kiếm tin nhắn, công ty...',
  'unreadFilter': 'Chưa đọc',
  'urgentFilter': 'Tuyển gấp',
  'interviewedFilter': 'Đã phỏng vấn',
  'savedFilter': 'Đã lưu',
  'pinnedLabel': 'Ghim',
  'allLabel': 'Tất cả',
  'respondsIn24h': 'Phản hồi trong 24h',
  'resume': 'CV',
  'uploadResume': 'Tải lên CV',
  'replaceResume': 'Thay thế CV',
  'deleteResume': 'Xóa CV',
  'viewResume': 'Xem CV',
  'skills': 'Kỹ năng',
  'experience': 'Kinh nghiệm',
  'education': 'Giáo dục',
  'resumeDocuments': 'CV & Tài liệu',
  'resumeFiles': 'TỆP',
  'browseFiles': 'Duyệt tệp',
  'uploadThankYou': 'Tải lên thành công',
  'uploadFailed': 'Tải lên thất bại',
  'replaceFailed': 'Thay thế thất bại',
  'deleteSuccess': 'Xóa thành công',
  'setDefaultSuccess': 'Đặt làm mặc định thành công',
  'replaceSuccess': 'Thay thế thành công',

  // Jobs
  'jobs': 'Việc làm',
  'jobTitle': 'Tiêu đề công việc',
  'company': 'Công ty',
  'location': 'Vị trí',
  'salary': 'Mức lương',
  'description': 'Mô tả',
  'requirements': 'Yêu cầu',
  'applyJob': 'Ứng tuyển',
  'appliedJobs': 'Việc làm đã ứng tuyển',
  'savedJobs': 'Việc làm đã lưu',
  'jobDetails': 'Chi tiết công việc',
  'noJobsFound': 'Không tìm thấy công việc',
  'applySuccess': 'Ứng tuyển thành công',
  'apply': 'Ứng tuyển',
  'favoriteJobs': 'Việc làm yêu thích',

  // Common
  'home': 'Trang chủ',
  'search': 'Tìm kiếm',
  'settings': 'Cài đặt',
  'language': 'Ngôn ngữ',
  'selectLanguage': 'Chọn ngôn ngữ',
  'notifications': 'Thông báo',
  'help': 'Trợ giúp',
  'about': 'Về ứng dụng',
  'version': 'Phiên bản',
  'loading': 'Đang tải...',
  'error': 'Lỗi',
  'errorMessage': 'Lỗi: ',
  'success': 'Thành công',
  'tryAgain': 'Thử lại',
  'noInternetConnection': 'Không có kết nối Internet',
  'somethingWentWrong': 'Có gì đó không ổn',
  'close': 'Đóng',
  'open': 'Mở',
  'yes': 'Có',
  'no': 'Không',
  'ok': 'OK',
  'contactUs': 'Liên hệ chúng tôi',
  'privacyPolicy': 'Chính sách bảo mật',
  'termsOfService': 'Điều khoản dịch vụ',
  'helpCenter': 'Trung tâm trợ giúp',
  'changePassword': 'Thay đổi mật khẩu',
  'pushNotifications': 'Thông báo đẩy',
  'account': 'TÀI KHOẢN',
  'privacy': 'BẢO MẬT',
  'support': 'HỖ TRỢ',
  'desiredPosition': 'Vị trí mong muốn',
  'yearsOfExperience': 'Năm kinh nghiệm',
  'positionDesiredTitle': 'Vị trí mong muốn: ',
  'exitApplication': 'Thoát ứng dụng',
  'coverLetter': 'Thư xin việc',
  'applySuccessMessage': 'Ứng tuyển thành công',
  'stepOfThree': 'BƯỚC 1 TRONG 3',
  'chooseYourRole': 'Chọn vai trò của bạn',
  'selectHowToUse': 'Chọn cách bạn muốn sử dụng nền tảng',
  'iAmCandidate': 'Tôi là ứng viên',
  'candidateDescription':
      'Tôi đang tìm các cơ hội sự nghiệp mới và muốn thể hiện tài năng của mình.',
  'iAmEmployer': 'Tôi là nhà tuyển dụng',
  'employerDescription':
      'Tôi đang tìm các ứng viên tài năng cho công ty của mình.',
  'next': 'Tiếp theo',
  'back': 'Quay lại',
  'selectRole': 'Vui lòng chọn vai trò để tiếp tục',
  'uploadNewResume': 'Tải lên CV mới',
  'uploadFileSize': 'PDF, DOCX tối đa 10MB',
  // Register Info Page
  'fullNameHint': 'Họ và tên',
  'fullNameRequired': 'Vui lòng nhập họ và tên',
  'fullNameLength': 'Họ và tên phải có ít nhất 2 ký tự',
  'emailAddressRequired': 'Email là bắt buộc',
  'passwordMinLength': 'Mật khẩu phải có ít nhất 6 ký tự',
  'confirmPasswordLabel': 'Xác nhận mật khẩu',
  'confirmPasswordHint': 'Xác nhận mật khẩu',
  'passwordMismatch': 'Mật khẩu không khớp',
  // Register Verify Email
  'stepOfThreeMsg': 'BƯỚC 3 TRONG 3',
  'otpVerification': 'Xác minh OTP',
  'emailVerificationMessage': 'Chúng tôi đã gửi liên kết xác nhận tới',
  'clickLinkMessage':
      'Nhấp vào liên kết trong email của bạn để kích hoạt tài khoản.',
  'confirmedEmail': 'Tôi đã xác nhận email',
  'didNotReceiveEmail': 'Không nhận được email?',
  'resendEmail': 'Gửi lại email',
  'requestNewCode': 'Yêu cầu mã mới trong',
  'verificationSuccess': 'Email xác minh thành công!',
  'verificationFailed': 'Xác minh email thất bại',
  'resendFailed': 'Gửi lại email thất bại',

  // Job Search & Details
  'searchJobTitle': 'Tìm kiếm chức danh công việc hoặc từ khóa',
  'clearFilters': 'Xóa bộ lọc',
  'noJobsMatch': 'Không có công việc nào phù hợp với bộ lọc của bạn.',
  'jobsFound': 'công việc được tìm thấy',
  'filters': 'Bộ lọc',
  'mostRelevant': 'Phù hợp nhất',
  'alreadyApplied': 'Đã ứng tuyển',
  'applyNow': 'Ứng tuyển ngay',
  'jobClosed': 'Công việc đã đóng',

  // Apply Job
  'applyForJob': 'Ứng tuyển công việc',
  'selectCV': 'Chọn CV',
  'chooseResumeForApplication':
      'Chọn hồ sơ bạn muốn sử dụng cho đơn ứng tuyển này.',
  'noCVFound': 'Không tìm thấy CV trong hồ sơ của bạn',
  'pleaseUploadCVBeforeApplying':
      'Vui lòng tải CV lên hồ sơ của bạn trước khi ứng tuyển.',
  'resumeSelection': 'Chọn hồ sơ',
  'finalReview': 'ĐÁNH GIÁ CUỐI CÙNG',
  'step1Of2': 'BƯỚC 1 TRONG 2',
  'step2Of2': 'Bước 2 trong 2',
  'successfullyApplied': 'Ứng tuyển thành công!',
  'applicationFailed': 'Ứng tuyển thất bại, vui lòng thử lại',
  'applicationSuccessMessage': 'Đơn ứng tuyển của bạn đã được gửi thành công!',
  'mustAddCVBeforeApplying': 'Vui lòng thêm CV vào hồ sơ trước khi ứng tuyển',

  // Apply Job - Additional
  'cancelButton': 'Hủy',
  'readyToApplyStatus': 'Sẵn sàng ứng tuyển',
  'optionalLabel': 'Tùy chọn',
  'goToProfile': 'Đi đến Hồ sơ',
  'coverLetterPlaceholder':
      'Giới thiệu bản thân với người quản lý tuyển dụng. Nêu bật các kỹ năng liên quan của bạn và tại sao bạn phù hợp với vai trò này...',
  'reviewSelectedCvTitle': 'Xem xét CV được chọn',
  'attachedToApplicationStatus': 'Đính kèm vào đơn ứng tuyển',
  'changeCvButton': 'Thay đổi CV',
  'submitApplicationButton': 'Nộp đơn ứng tuyển',
  'submittingButton': 'Đang nộp...',
  'termsAgreement': 'Bằng cách nộp, bạn đồng ý với',
  'applicationSentSuccess': 'Đơn ứng tuyển\nđã được gửi thành công!',
  'applicationReceivedMessage': 'Đơn ứng tuyển của bạn cho ',
  'atLabel': ' tại ',
  'hasBeenReceived': ' đã được nhận.',
  'viewApplicationStatusButton': 'Xem trạng thái ứng tuyển',
  'backToHomeButton': 'Quay lại Trang chủ',
  'nextButton': 'Tiếp theo',

  // Home Page
  'homePageTitle': 'Trang chủ',
  'dashboardTooltip': 'Đi đến Bảng điều khiển',
  'recommendedJobsTitle': 'Công việc được đề xuất',
  'recentJobPostingsTitle': 'Các bài đăng công việc gần đây',
  'searchResultsTitle': 'Kết quả tìm kiếm cho',
  'noJobsFoundMessage': 'Không tìm thấy công việc',
  'loadMoreButton': 'Tải thêm',

  // Interview Schedule
  'interviewScheduleTitle': 'Lịch phỏng vấn',
  'noInterviewsMessage': 'Chưa có lịch phỏng vấn',
  'statusAccepted': 'Đã xác nhận',
  'statusRejected': 'Đã từ chối',
  'statusReschedule': 'Yêu cầu đổi lịch',
  'statusPending': 'Chờ phản hồi',
  'declineButton': 'Từ chối',
  'rescheduleButton': 'Đổi lịch',
  'acceptButton': 'Đồng ý',
  'scheduleConfirmedMessage': 'Đã xác nhận lịch phỏng vấn!',
  'scheduleDeclinedMessage': 'Đã từ chối lịch phỏng vấn',
  'rescheduleRequestedMessage': 'Đã yêu cầu đổi lịch',
  'contactLabel': 'Liên hệ:',
  'noLocationText': 'Không có địa điểm',
  'notAvailable': 'Không có sẵn',

  // Applications Page
  'applicationHistoryTitle': 'Lịch sử ứng tuyển',
  'appliedTabLabel': 'Đã ứng tuyển',
  'interviewsTabLabel': 'Phỏng vấn',
  'acceptedTabLabel': 'Được chấp nhận',
  'couldNotLoadProfileMessage': 'Không thể tải hồ sơ',
  'retryButton': 'Thử lại',
  'noApplicationsFoundMessage': 'Không tìm thấy ứng tuyển',
  'noApplicationsFoundDescription':
      'Các ứng tuyển của bạn cho danh mục này sẽ xuất hiện ở đây',
  'appliedOnLabel': 'Ứng tuyển vào',
  'withdrawButton': 'Rút hồ sơ',
  'withdrawConfirmTitle': 'Rút hồ sơ?',
  'withdrawConfirmMessage': 'Bạn có chắc chắn muốn rút hồ sơ ứng tuyển này?',
  'withdrawSuccessMessage': 'Đã rút hồ sơ thành công',
  'withdrawFailureMessage': 'Rút hồ sơ thất bại',

  // Messages Page
  'messagesPageTitle': 'Tin nhắn',
  'fromEmployersSubtitle': 'Từ nhà tuyển dụng',
  'messageSearchPlaceholder': 'Tìm kiếm tin nhắn, công ty...',
  'unreadFilterLabel': 'Chưa đọc',
  'urgentHiringFilterLabel': 'Tuyển gấp',
  'interviewedFilterLabel': 'Đã phỏng vấn',
  'savedFilterLabel': 'Đã lưu',
  'pinnedSectionLabel': 'Ghim',
  'allSectionLabel': 'Tất cả',
  'respondWithin24hTag': 'Phản hồi trong 24h',
  'pinnedTag': 'Ghim',

  // Welcome Page
  'welcomeTitle': 'Tìm công việc mơ ước của bạn',
  'welcomeDescription':
      'Khám phá hàng nghìn cơ hội việc làm\nvà bắt đầu hành trình sự nghiệp của bạn hôm nay',

  // Forgot Password
  'checkEmailTitle': 'Kiểm tra email của bạn',
  'otpSentMessage': 'Chúng tôi đã gửi OTP 6 chữ số đến',
  'enterOtpPlaceholder': 'Nhập OTP',
  'verifyOtpButton': 'Xác minh OTP',
  'insufficientOtpError': 'Vui lòng nhập đủ 6 số OTP',
  'invalidOtpError': 'OTP không hợp lệ',
  'expiredOtpError': 'OTP không hợp lệ hoặc đã hết hạn',
  'otpResendMessage': 'Không nhận được mã?',
  'resendButton': 'Gửi lại',
  'otpResentSuccess': 'OTP đã được gửi lại',
  'resendFailure': 'Gửi lại thất bại:',
  'employerDashboard': 'Bảng điều khiển',
  'overview': 'Tổng quan',
  'last30Days': '30 ngày qua',
  'activeJobs': 'Công việc đang mở',
  'applicants': 'Ứng viên',
  'interviewsCount': 'Phỏng vấn',
  'recentActivities': 'Hoạt động gần đây',
  'viewAll': 'Xem tất cả',
  'manageJobs': 'Quản lý công việc',
  'noJobsYet': 'Chưa có công việc nào',
  'createFirstJobPost':
      'Tạo bài đăng tuyển dụng đầu tiên của bạn để bắt đầu nhận hồ sơ ứng tuyển.',
  'postNewJob': 'Đăng việc mới',
  'draftJobs': 'Bản nháp',
  'closedJobs': 'Công việc đã đóng',
  'reopenJobTitle': 'Mở lại công việc?',
  'reopenJobConfirm': 'Mở lại công việc này?',
  'deleteJobTitle': 'Xóa công việc?',
  'deleteJobConfirm': 'Xóa công việc này?',
  'closeJobTitle': 'Đóng công việc?',
  'closeJobConfirm': 'Đóng công việc này? Bạn có thể mở lại sau.',
  'jobReopenedSuccess': 'Mở lại công việc thành công.',
  'jobDeleted': 'Đã xóa công việc.',
  'jobClosedSuccess': 'Đã đóng công việc.',
  'noJobsInTab': 'Chưa có công việc nào trong tab này',
  'tryCreatingNewJob': 'Thử tạo bài đăng mới hoặc chuyển sang tab khác.',
  'boostFeatureComingSoon': 'Tính năng đẩy tin sắp ra mắt.',
  'editJob': 'Chỉnh sửa công việc',
  'postANewJob': 'Đăng công việc mới',
  'saveDraft': 'Lưu bản nháp',
  'previewJob': 'Xem trước công việc',
  'nextStep': 'Bước tiếp theo',
  'jobTitleRequired': 'Tiêu đề công việc là bắt buộc',
  'pleaseChooseCategory': 'Vui lòng chọn danh mục',
  'locationRequired': 'Địa điểm là bắt buộc',
  'descriptionRequired': 'Mô tả công việc là bắt buộc',
  'requirementsRequired': 'Yêu cầu công việc là bắt buộc',
  'employmentTypeRequired': 'Loại hình công việc là bắt buộc',
  'positionsGreaterThanZero': 'Số lượng tuyển dụng phải lớn hơn 0',
  'chooseDeadline': 'Vui lòng chọn hạn chót ứng tuyển',
  'addSalaryRange': 'Vui lòng thêm mức lương hoặc đánh dấu là thỏa thuận',
  'jobTitleDraftRequired': 'Tiêu đề công việc là bắt buộc để lưu bản nháp',
  'jobUpdatedSuccess': 'Cập nhật công việc thành công!',
  'jobPostedSuccess': 'Đăng công việc thành công!',
  'draftSavedSuccess': 'Lưu bản nháp thành công!',
  'example': 'VD:',
  'selectCategory': 'Chọn danh mục',
  'negotiable': 'Thỏa thuận',
  'openPositions': 'Số lượng tuyển dụng',
  'applicationDeadline': 'Hạn chót ứng tuyển',
  'selectDate': 'Chọn ngày',
  'perksAndBenefits': 'Quyền lợi & Phúc lợi',
  'salaryRange': 'Mức lương',
  'minSalary': 'Lương tối thiểu',
  'maxSalary': 'Lương tối đa',
  'perMonth': '/ tháng',
  'jobDescription': 'Mô tả công việc',
  'jobRequirements': 'Yêu cầu công việc',
  'skillsAndTags': 'Kỹ năng & Thẻ',
  'addSkillHint': 'Thêm kỹ năng và nhấn Enter',
  'employmentType': 'Loại hình công việc',
  'fullTime': 'Toàn thời gian',
  'partTime': 'Bán thời gian',
  'contract': 'Hợp đồng',
  'freelance': 'Tự do',
  'internship': 'Thực tập',
  'remote': 'Từ xa',
  'experienceLevel': 'Cấp bậc kinh nghiệm',
  'entryLevel': 'Mới bắt đầu',
  'midLevel': 'Trung cấp',
  'seniorLevel': 'Cao cấp',
  'leadLevel': 'Trưởng nhóm',
  'clearAll': 'Xóa tất cả',
  'showResults': 'Xem kết quả',
  'enterLocationHint': 'Nhập thành phố, tỉnh hoặc quốc gia',
  'jobSaved': 'Đã lưu công việc!',
  'addedToFavorites': 'Đã thêm vào\ndanh sách yêu thích',
  'applicantsSoFar': 'ứng viên cho đến nay',
  'resumePreview': 'Xem trước Hồ sơ',
  'filesCount': 'TỆP',
  'replacedSuccess': 'Thay thế thành công',
  'couldNotOpenUrl': 'Không thể mở URL CV',
  'uploadedLabel': 'Đã tải lên',
  'applicationTimeline': 'Tiến trình ứng tuyển',
  'applicationSubmitted': 'Đã gửi hồ sơ',
  'underReview': 'Đang xét duyệt',
  'shortlistedInterview': 'Hồ sơ tiềm năng/Phỏng vấn',
  'decision': 'Quyết định',
  'yourApplication': 'Hồ sơ của bạn',
  'attachedResume': 'Hồ sơ đính kèm',
  'withdrawConfirmMessageUndo':
      'Bạn có chắc chắn muốn rút hồ sơ? Hành động này không thể hoàn tác.',
  'pendingReview': 'Chờ xét duyệt',
  'employerReviewing': 'Nhà tuyển dụng đang xem',
  'interviewInvited': 'Đã mời phỏng vấn',
  'acceptedHired': 'Đã trúng tuyển',
  'notSelected': 'Không phù hợp',
  'withdrawnByYou': 'Bạn đã rút hồ sơ',
  'currentStatus': 'Trạng thái hiện tại',
  'applicationStatus': 'Trạng thái ứng tuyển',
  'negotiableSubtitle': 'Cho ứng viên biết mức lương có thể thỏa thuận.',
};
