final Map<String, String> vietStrings = {
  // Auth
  'email': 'Email',
  'password': 'Mật khẩu',
  'confirmPassword': 'Xác nhận mật khẩu',
  'login': 'Đăng nhập',
  'register': 'Đăng ký',
  'logout': 'Đăng xuất',
  'forgotPassword': 'Quên mật khẩu?',
  'resetPassword': 'Đặt lại mật khẩu',
  'signUp': 'Đăng ký',
  'signIn': 'Đăng nhập',
  'signInWithGoogle': 'Đăng nhập với Google',
  'signInWithFacebook': 'Đăng nhập với Facebook',
  'alreadyHaveAccount': 'Đã có tài khoản?',
  'dontHaveAccount': 'Chưa có tài khoản?',
  'invalidEmail': 'Vui lòng nhập email hợp lệ',
  'passwordTooShort': 'Mật khẩu phải có ít nhất 6 ký tự',
  'passwordsDoNotMatch': 'Mật khẩu không khớp',
  'emailAlreadyExists': 'Email đã tồn tại',
  'invalidCredentials': 'Email hoặc mật khẩu không đúng',
  'loginSuccess': 'Đăng nhập thành công',
  'registerSuccess': 'Đăng ký thành công',
  'logoutSuccess': 'Đăng xuất thành công',
  'emailAddressHint': 'Địa chỉ Email',
  'passwordHint': 'Mật khẩu',
  'rememberMe': 'Ghi nhớ tôi',
  'welcomeBack': 'Chào mừng trở lại',
  'signInToContinue': 'Đăng nhập để tiếp tục tìm kiếm việc làm của bạn',
  'dontHaveAccountQuestion': 'Chưa có tài khoản?',
  'loginError': 'Đăng nhập thất bại',
  'emailRequired': 'Email là bắt buộc',
  'invalidEmailFormat': 'Định dạng email không hợp lệ',
  'passwordRequired': 'Mật khẩu là bắt buộc',

  // Profile
  'profile': 'Hồ sơ',
  'editProfile': 'Chỉnh sửa hồ sơ',
  'fullName': 'Họ và tên',
  'phoneNumber': 'Số điện thoại',
  'address': 'Địa chỉ',
  'bio': 'Giới thiệu',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'delete': 'Xóa',
  'close': 'Đóng',
  'edit': 'Chỉnh sửa',
  'info': 'Thông tin',
  'favorites': 'Yêu thích',
  'profileUpdated': 'Hồ sơ đã được cập nhật thành công',
  'messagesTitle': 'Tin nhắn',
  'fromRecruiters': 'Từ nhà tuyển dụng',
  'searchMessagesHint': 'Tìm kiếm tin nhắn, công ty...',
  'unreadFilter': 'Chưa đọc',
  'urgentFilter': 'Tuyển gấp',
  'interviewedFilter': 'Đã phỏng vấn',
  'savedFilter': 'Đã lưu',
  'pinnedLabel': 'Ghim',
  'allLabel': 'Tất cả',
  'respondsIn24h': 'Phản hồi trong 24h',
  'resume': 'CV',
  'uploadResume': 'Tải lên CV',
  'replaceResume': 'Thay thế CV',
  'deleteResume': 'Xóa CV',
  'viewResume': 'Xem CV',
  'skills': 'Kỹ năng',
  'experience': 'Kinh nghiệm',
  'education': 'Giáo dục',
  'resumeDocuments': 'CV & Tài liệu',
  'resumeFiles': 'TỆP',
  'browseFiles': 'Duyệt tệp',
  'uploadThankYou': 'Tải lên thành công',
  'uploadFailed': 'Tải lên thất bại',
  'replaceFailed': 'Thay thế thất bại',
  'deleteSuccess': 'Xóa thành công',
  'setDefaultSuccess': 'Đặt làm mặc định thành công',
  'replaceSuccess': 'Thay thế thành công',

  // Jobs
  'jobs': 'Việc làm',
  'jobTitle': 'Tiêu đề công việc',
  'company': 'Công ty',
  'location': 'Vị trí',
  'salary': 'Mức lương',
  'description': 'Mô tả',
  'requirements': 'Yêu cầu',
  'applyJob': 'Ứng tuyển',
  'appliedJobs': 'Việc làm đã ứng tuyển',
  'savedJobs': 'Việc làm đã lưu',
  'jobDetails': 'Chi tiết công việc',
  'noJobsFound': 'Không tìm thấy công việc',
  'applySuccess': 'Ứng tuyển thành công',
  'apply': 'Ứng tuyển',
  'favoriteJobs': 'Việc làm yêu thích',

  // Common
  'home': 'Trang chủ',
  'search': 'Tìm kiếm',
  'settings': 'Cài đặt',
  'language': 'Ngôn ngữ',
  'selectLanguage': 'Chọn ngôn ngữ',
  'notifications': 'Thông báo',
  'help': 'Trợ giúp',
  'about': 'Về ứng dụng',
  'version': 'Phiên bản',
  'loading': 'Đang tải...',
  'error': 'Lỗi',
  'errorMessage': 'Lỗi: ',
  'success': 'Thành công',
  'tryAgain': 'Thử lại',
  'noInternetConnection': 'Không có kết nối Internet',
  'somethingWentWrong': 'Có gì đó không ổn',
  'close': 'Đóng',
  'open': 'Mở',
  'yes': 'Có',
  'no': 'Không',
  'ok': 'OK',
  'contactUs': 'Liên hệ chúng tôi',
  'privacyPolicy': 'Chính sách bảo mật',
  'termsOfService': 'Điều khoản dịch vụ',
  'helpCenter': 'Trung tâm trợ giúp',
  'privacyPolicyContent':
      'Chính sách bảo mật\n\n'
      '1) Dữ liệu thu thập\n'
      '- Thông tin hồ sơ, liên hệ, và hoạt động trong ứng dụng.\n'
      '- Nhật ký sử dụng cơ bản để cải thiện trải nghiệm.\n\n'
      '2) Mục đích sử dụng\n'
      '- Kết nối nhà tuyển dụng và ứng viên.\n'
      '- Gửi thông báo liên quan đến tuyển dụng.\n'
      '- Hỗ trợ chăm sóc khách hàng và bảo mật tài khoản.\n\n'
      '3) Bảo vệ dữ liệu\n'
      '- Dữ liệu được lưu trữ an toàn và chỉ truy cập khi cần thiết.\n'
      '- Bạn có thể yêu cầu chỉnh sửa hoặc xóa thông tin.\n\n'
      '4) Chia sẻ dữ liệu\n'
      '- Chỉ chia sẻ trong phạm vi chức năng tuyển dụng.\n'
      '- Không bán dữ liệu cho bên thứ ba.',
  'termsOfServiceContent':
      'Điều khoản dịch vụ\n\n'
      '1) Tài khoản\n'
      '- Cung cấp thông tin chính xác và cập nhật.\n'
      '- Tự chịu trách nhiệm về bảo mật tài khoản.\n\n'
      '2) Nội dung\n'
      '- Không đăng tải nội dung vi phạm pháp luật hoặc gây hiểu nhầm.\n'
      '- Nhà tuyển dụng chịu trách nhiệm về thông tin tuyển dụng.\n\n'
      '3) Hành vi bị cấm\n'
      '- Gian lận, spam, hoặc khai thác hệ thống trái phép.\n'
      '- Tấn công hoặc làm gián đoạn dịch vụ.\n\n'
      '4) Thay đổi điều khoản\n'
      '- Điều khoản có thể cập nhật và sẽ thông báo trong ứng dụng.',
  'helpCenterContent':
      'Trung tâm trợ giúp\n\n'
      'Chúng tôi sẵn sàng hỗ trợ các vấn đề sau:\n'
      '- Không nhận được thông báo.\n'
      '- Lỗi đăng nhập hoặc xác minh email.\n'
      '- Cập nhật hồ sơ, bài đăng tuyển dụng, và ứng tuyển.\n\n'
      'Gợi ý tự xử lý nhanh:\n'
      '1) Kiểm tra kết nối mạng.\n'
      '2) Cập nhật ứng dụng lên phiên bản mới nhất.\n'
      '3) Đăng xuất và đăng nhập lại.\n\n'
      'Nếu vẫn gặp lỗi, hãy liên hệ với chúng tôi.',
  'contactUsContent':
      'Liên hệ với chúng tôi\n\n'
      'Email: support@jobgo.vn\n'
      'Hotline: 1900 123 456 (08:30 - 18:00)\n'
      'Địa chỉ: 68 Nguyen Hue, Quan 1, TP. Ho Chi Minh\n\n'
      'Chúng tôi phản hồi trong vòng 24 - 48 giờ làm việc.',
  'changePassword': 'Thay đổi mật khẩu',
  'pushNotifications': 'Thông báo đẩy',
  'account': 'TÀI KHOẢN',
  'privacy': 'BẢO MẬT',
  'support': 'HỖ TRỢ',
  'desiredPosition': 'Vị trí mong muốn',
  'yearsOfExperience': 'Năm kinh nghiệm',
  'positionDesiredTitle': 'Vị trí mong muốn: ',
  'exitApplication': 'Thoát ứng dụng',
  'coverLetter': 'Thư xin việc',
  'applySuccessMessage': 'Ứng tuyển thành công',
  'stepOfThree': 'BƯỚC 1 TRONG 3',
  'chooseYourRole': 'Chọn vai trò của bạn',
  'selectHowToUse': 'Chọn cách bạn muốn sử dụng nền tảng',
  'iAmCandidate': 'Tôi là ứng viên',
  'candidateDescription':
      'Tôi đang tìm các cơ hội sự nghiệp mới và muốn thể hiện tài năng của mình.',
  'iAmEmployer': 'Tôi là nhà tuyển dụng',
  'employerDescription':
      'Tôi đang tìm các ứng viên tài năng cho công ty của mình.',
  'next': 'Tiếp theo',
  'back': 'Quay lại',
  'selectRole': 'Vui lòng chọn vai trò để tiếp tục',
  'uploadNewResume': 'Tải lên CV mới',
  'uploadFileSize': 'PDF, DOCX, TXT tối đa 10MB',
  // Register Info Page
  'fullNameHint': 'Họ và tên',
  'fullNameRequired': 'Vui lòng nhập họ và tên',
  'fullNameLength': 'Họ và tên phải có ít nhất 2 ký tự',
  'emailAddressRequired': 'Email là bắt buộc',
  'passwordMinLength': 'Mật khẩu phải có ít nhất 6 ký tự',
  'confirmPasswordLabel': 'Xác nhận mật khẩu',
  'confirmPasswordHint': 'Xác nhận mật khẩu',
  'passwordMismatch': 'Mật khẩu không khớp',
  // Register Verify Email
  'stepOfThreeMsg': 'BƯỚC 3 TRONG 3',
  'otpVerification': 'Xác minh OTP',
  'emailVerificationMessage': 'Chúng tôi đã gửi liên kết xác nhận tới',
  'clickLinkMessage':
      'Nhấp vào liên kết trong email của bạn để kích hoạt tài khoản.',
  'confirmedEmail': 'Tôi đã xác nhận email',
  'didNotReceiveEmail': 'Không nhận được email?',
  'resendEmail': 'Gửi lại email',
  'requestNewCode': 'Yêu cầu mã mới trong',
  'verificationSuccess': 'Email xác minh thành công!',
  'verificationFailed': 'Xác minh email thất bại',
  'resendFailed': 'Gửi lại email thất bại',

  // Job Search & Details
  'searchJobTitle': 'Tìm kiếm chức danh công việc hoặc từ khóa',
  'clearFilters': 'Xóa bộ lọc',
  'noJobsMatch': 'Không có công việc nào phù hợp với bộ lọc của bạn.',
  'jobsFound': 'công việc được tìm thấy',
  'filters': 'Bộ lọc',
  'mostRelevant': 'Phù hợp nhất',
  'alreadyApplied': 'Đã ứng tuyển',
  'applyNow': 'Ứng tuyển ngay',
  'jobClosed': 'Công việc đã đóng',

  // Apply Job
  'applyForJob': 'Ứng tuyển công việc',
  'selectCV': 'Chọn CV',
  'chooseResumeForApplication':
      'Chọn hồ sơ bạn muốn sử dụng cho đơn ứng tuyển này.',
  'noCVFound': 'Không tìm thấy CV trong hồ sơ của bạn',
  'pleaseUploadCVBeforeApplying':
      'Vui lòng tải CV lên hồ sơ của bạn trước khi ứng tuyển.',
  'resumeSelection': 'Chọn hồ sơ',
  'finalReview': 'ĐÁNH GIÁ CUỐI CÙNG',
  'step1Of2': 'BƯỚC 1 TRONG 2',
  'step2Of2': 'Bước 2 trong 2',
  'successfullyApplied': 'Ứng tuyển thành công!',
  'applicationFailed': 'Ứng tuyển thất bại, vui lòng thử lại',
  'applicationSuccessMessage': 'Đơn ứng tuyển của bạn đã được gửi thành công!',
  'mustAddCVBeforeApplying': 'Vui lòng thêm CV vào hồ sơ trước khi ứng tuyển',

  // Apply Job - Additional
  'aiCvFit': 'Độ phù hợp AI',
  'aiInsight': 'Phân tích AI',
  'aiMatch': 'Phù hợp AI',
  'analyze': 'Phân tích',
  'analyzeCv': 'Phân tích CV',
  'reanalyze': 'Phân tích lại',
  'aiAnalysisSupportsPdfOnly': 'Phân tích AI hiện hỗ trợ PDF, DOCX và TXT.',
  'missingJobDetailsForAiAnalysis':
      'Thiếu thông tin công việc để phân tích AI.',
  'noAiAnalysisYet':
      'Chưa có phân tích AI. Hãy chạy phân tích để xem điểm phù hợp và gợi ý phỏng vấn.',
  'missingSkillsLabel': 'Kỹ năng còn thiếu:',
  'interviewChecksLabel': 'Cần kiểm tra khi phỏng vấn:',
  'suggestionsLabel': 'Gợi ý:',
  'coverLetterTipsLabel': 'Gợi ý cover letter:',
  'analyzeFailed': 'Phân tích thất bại',
  'invalidJobIdentifier': 'Job không hợp lệ.',
  'refreshFailed': 'Tải lại thất bại',
  'viewProfile': 'Xem hồ sơ',
  'message': 'Nhắn tin',
  'chooseProfileImage': 'Chọn ảnh đại diện',
  'takeNewPhoto': 'Chụp ảnh mới',
  'chooseFromLibrary': 'Chọn từ thư viện',
  'cancelButton': 'Hủy',
  'readyToApplyStatus': 'Sẵn sàng ứng tuyển',
  'optionalLabel': 'Tùy chọn',
  'goToProfile': 'Đi đến Hồ sơ',
  'coverLetterPlaceholder':
      'Giới thiệu bản thân với người quản lý tuyển dụng. Nêu bật các kỹ năng liên quan của bạn và tại sao bạn phù hợp với vai trò này...',
  'reviewSelectedCvTitle': 'Xem xét CV được chọn',
  'attachedToApplicationStatus': 'Đính kèm vào đơn ứng tuyển',
  'changeCvButton': 'Thay đổi CV',
  'submitApplicationButton': 'Nộp đơn ứng tuyển',
  'submittingButton': 'Đang nộp...',
  'termsAgreement': 'Bằng cách nộp, bạn đồng ý với',
  'applicationSentSuccess': 'Đơn ứng tuyển\nđã được gửi thành công!',
  'applicationReceivedMessage': 'Đơn ứng tuyển của bạn cho ',
  'atLabel': ' tại ',
  'hasBeenReceived': ' đã được nhận.',
  'viewApplicationStatusButton': 'Xem trạng thái ứng tuyển',
  'backToHomeButton': 'Quay lại Trang chủ',
  'nextButton': 'Tiếp theo',

  // Home Page
  'homePageTitle': 'Trang chủ',
  'dashboardTooltip': 'Đi đến Bảng điều khiển',
  'recommendedJobsTitle': 'Công việc được đề xuất',
  'recentJobPostingsTitle': 'Các bài đăng công việc gần đây',
  'searchResultsTitle': 'Kết quả tìm kiếm cho',
  'noJobsFoundMessage': 'Không tìm thấy công việc',
  'loadMoreButton': 'Tải thêm',

  // Interview Schedule
  'interviewScheduleTitle': 'Lịch phỏng vấn',
  'noInterviewsMessage': 'Chưa có lịch phỏng vấn',
  'statusAccepted': 'Đã xác nhận',
  'statusRejected': 'Đã từ chối',
  'statusReschedule': 'Yêu cầu đổi lịch',
  'statusPending': 'Chờ phản hồi',
  'declineButton': 'Từ chối',
  'rescheduleButton': 'Đổi lịch',
  'acceptButton': 'Đồng ý',
  'scheduleConfirmedMessage': 'Đã xác nhận lịch phỏng vấn!',
  'scheduleDeclinedMessage': 'Đã từ chối lịch phỏng vấn',
  'rescheduleRequestedMessage': 'Đã yêu cầu đổi lịch',
  'contactLabel': 'Liên hệ:',
  'noLocationText': 'Không có địa điểm',
  'notAvailable': 'Không có sẵn',

  // Applications Page
  'applicationHistoryTitle': 'Lịch sử ứng tuyển',
  'appliedTabLabel': 'Đã ứng tuyển',
  'interviewsTabLabel': 'Phỏng vấn',
  'acceptedTabLabel': 'Được chấp nhận',
  'couldNotLoadProfileMessage': 'Không thể tải hồ sơ',
  'retryButton': 'Thử lại',
  'noApplicationsFoundMessage': 'Không tìm thấy ứng tuyển',
  'noApplicationsFoundDescription':
      'Các ứng tuyển của bạn cho danh mục này sẽ xuất hiện ở đây',
  'appliedOnLabel': 'Ứng tuyển vào',
  'withdrawButton': 'Rút hồ sơ',
  'withdrawConfirmTitle': 'Rút hồ sơ?',
  'withdrawConfirmMessage': 'Bạn có chắc chắn muốn rút hồ sơ ứng tuyển này?',
  'withdrawSuccessMessage': 'Đã rút hồ sơ thành công',
  'withdrawFailureMessage': 'Rút hồ sơ thất bại',

  // Messages Page
  'messagesPageTitle': 'Tin nhắn',
  'fromEmployersSubtitle': 'Từ nhà tuyển dụng',
  'messageSearchPlaceholder': 'Tìm kiếm tin nhắn, công ty...',
  'unreadFilterLabel': 'Chưa đọc',
  'urgentHiringFilterLabel': 'Tuyển gấp',
  'interviewedFilterLabel': 'Đã phỏng vấn',
  'savedFilterLabel': 'Đã lưu',
  'pinnedSectionLabel': 'Ghim',
  'allSectionLabel': 'Tất cả',
  'respondWithin24hTag': 'Phản hồi trong 24h',
  'pinnedTag': 'Ghim',

  // Welcome Page
  'welcomeTitle': 'Tìm công việc mơ ước của bạn',
  'welcomeDescription':
      'Khám phá hàng nghìn cơ hội việc làm\nvà bắt đầu hành trình sự nghiệp của bạn hôm nay',

  // Forgot Password
  'checkEmailTitle': 'Kiểm tra email của bạn',
  'otpSentMessage': 'Chúng tôi đã gửi OTP 6 chữ số đến',
  'enterOtpPlaceholder': 'Nhập OTP',
  'verifyOtpButton': 'Xác minh OTP',
  'insufficientOtpError': 'Vui lòng nhập đủ 6 số OTP',
  'invalidOtpError': 'OTP không hợp lệ',
  'expiredOtpError': 'OTP không hợp lệ hoặc đã hết hạn',
  'otpResendMessage': 'Không nhận được mã?',
  'resendButton': 'Gửi lại',
  'otpResentSuccess': 'OTP đã được gửi lại',
  'resendFailure': 'Gửi lại thất bại:',
  'employerDashboard': 'Bảng điều khiển',
  'overview': 'Tổng quan',
  'last30Days': '30 ngày qua',
  'activeJobs': 'Đang mở',
  'applicants': 'Ứng viên',
  'interviewsCount': 'Phỏng vấn',
  'recentActivities': 'Hoạt động gần đây',
  'viewAll': 'Xem tất cả',
  'manageJobs': 'Quản lý công việc',
  'noJobsYet': 'Chưa có công việc nào',
  'createFirstJobPost':
      'Tạo bài đăng tuyển dụng đầu tiên của bạn để bắt đầu nhận hồ sơ ứng tuyển.',
  'postNewJob': 'Đăng việc mới',
  'needToHire': 'Cần tuyển người?',
  'postNewJobDescription': 'Đăng tin tuyển dụng ngay hôm nay',
  'draftJobs': 'Bản nháp',
  'closedJobs': 'Đã đóng',
  'allJobs': 'Tất cả',
  'activeStatus': 'ĐANG MỞ',
  'closedStatus': 'ĐÃ ĐÓNG',
  'draftStatus': 'NHÁP',
  'pendingStatus': 'Chờ duyệt',
  'untitledJob': 'Công việc chưa đặt tên',
  'viewApplicants': 'Xem ứng viên →',
  'viewHistory': 'Xem lịch sử →',
  'reopen': 'Mở lại',
  'reopenJobTitle': 'Mở lại công việc?',
  'reopenJobConfirm': 'Mở lại công việc này?',
  'deleteJobTitle': 'Xóa công việc?',
  'deleteJobConfirm': 'Xóa công việc này?',
  'closeJobTitle': 'Đóng công việc?',
  'closeJobConfirm': 'Đóng công việc này? Bạn có thể mở lại sau.',
  'jobReopenedSuccess': 'Mở lại công việc thành công.',
  'jobDeleted': 'Đã xóa công việc.',
  'jobClosedSuccess': 'Đã đóng công việc.',
  'noJobsInTab': 'Chưa có công việc nào trong tab này',
  'tryCreatingNewJob': 'Thử tạo bài đăng mới hoặc chuyển sang tab khác.',
  'boostFeatureComingSoon': 'Tính năng đẩy tin sắp ra mắt.',
  'couldNotLoadJobs': 'Không tải được tin tuyển dụng.',
  'editJob': 'Chỉnh sửa công việc',
  'postANewJob': 'Đăng công việc mới',
  'reviewJobChanges': 'Xem lại thay đổi',
  'previewJobPost': 'Xem trước tin tuyển dụng',
  'confirmAndPost': 'Xác nhận & Đăng',
  'publishJob': 'Đăng công việc',
  'updateJob': 'Cập nhật công việc',
  'backToEdit': 'Quay lại chỉnh sửa',
  'addAnotherJob': 'Thêm công việc khác',
  'saveDraft': 'Lưu bản nháp',
  'previewJob': 'Xem trước công việc',
  'nextStep': 'Bước tiếp theo',
  'jobTitleRequired': 'Tiêu đề công việc là bắt buộc',
  'pleaseChooseCategory': 'Vui lòng chọn danh mục',
  'locationRequired': 'Địa điểm là bắt buộc',
  'descriptionRequired': 'Mô tả công việc là bắt buộc',
  'requirementsRequired': 'Yêu cầu công việc là bắt buộc',
  'employmentTypeRequired': 'Loại hình công việc là bắt buộc',
  'positionsGreaterThanZero': 'Số lượng tuyển dụng phải lớn hơn 0',
  'chooseDeadline': 'Vui lòng chọn hạn chót ứng tuyển',
  'addSalaryRange': 'Vui lòng thêm mức lương hoặc đánh dấu là thỏa thuận',
  'jobTitleDraftRequired': 'Tiêu đề công việc là bắt buộc để lưu bản nháp',
  'jobUpdatedSuccess': 'Cập nhật công việc thành công!',
  'jobPostedSuccess': 'Đăng công việc thành công!',
  'draftSavedSuccess': 'Lưu bản nháp thành công!',
  'example': 'VD:',
  'selectCategory': 'Chọn danh mục',
  'jobTitleExampleHint': 'VD: Senior Flutter Developer',
  'experienceExampleHint': 'VD: 5+ năm kinh nghiệm...',
  'softwareDevelopment': 'Phát triển phần mềm',
  'designCreative': 'Thiết kế & Sáng tạo',
  'productManagement': 'Quản lý sản phẩm',
  'dataScienceAnalytics': 'Khoa học dữ liệu & Phân tích',
  'devOpsInfrastructure': 'DevOps & Hạ tầng',
  'marketingGrowth': 'Marketing & Tăng trưởng',
  'salesBusinessDevelopment': 'Kinh doanh & Phát triển thị trường',
  'humanResources': 'Nhân sự',
  'financeAccounting': 'Tài chính & Kế toán',
  'operationsAdministration': 'Vận hành & Hành chính',
  'negotiable': 'Thỏa thuận',
  'openPositions': 'Số lượng tuyển dụng',
  'opening': 'vị trí tuyển',
  'openings': 'vị trí tuyển',
  'applicationDeadline': 'Hạn chót ứng tuyển',
  'selectDate': 'Chọn ngày',
  'perksAndBenefits': 'Quyền lợi & Phúc lợi',
  'noBenefitsAddedYet': 'Chưa có quyền lợi nào.',
  'includedBenefit': 'Quyền lợi đi kèm',
  'salaryRange': 'Mức lương',
  'minSalary': 'Lương tối thiểu',
  'maxSalary': 'Lương tối đa',
  'fromSalary': 'Từ',
  'upToSalary': 'Đến',
  'perMonth': '/ tháng',
  'jobDescription': 'Mô tả công việc',
  'jobRequirements': 'Yêu cầu công việc',
  'noDescriptionProvidedYet': 'Chưa có mô tả.',
  'noRequirementsListedYet': 'Chưa có yêu cầu.',
  'skillsAndTags': 'Kỹ năng & Thẻ',
  'addSkillHint': 'Thêm kỹ năng và nhấn Enter',
  'employmentType': 'Loại hình công việc',
  'fullTime': 'Toàn thời gian',
  'partTime': 'Bán thời gian',
  'contract': 'Hợp đồng',
  'freelance': 'Tự do',
  'internship': 'Thực tập',
  'remote': 'Từ xa',
  'addSkills': 'Thêm kỹ năng',
  'addCustom': '+ Thêm tùy chỉnh',
  'customSkillComingSoon': 'Tính năng thêm kỹ năng tùy chỉnh sắp ra mắt',
  'figma': 'Figma',
  'uiDesign': 'Thiết kế UI',
  'flutter': 'Flutter',
  'react': 'React',
  'communication': 'Giao tiếp',
  'leadership': 'Lãnh đạo',
  'healthInsurance': 'Bảo hiểm sức khỏe',
  'gym': 'Phòng gym',
  'bonus': 'Thưởng',
  'remoteWork': 'Làm việc từ xa',
  'paidLeave': 'Nghỉ phép có lương',
  'flexibleHours': 'Giờ làm linh hoạt',
  'stockOptions': 'Cổ phần thưởng',
  'unknownCompany': 'Công ty chưa xác định',
  'locationNotSet': 'Chưa có địa điểm',
  'verified': 'Đã xác minh',
  'readyToPublish': 'Sẵn sàng đăng',
  'missing': 'Thiếu',
  'statusDraft': 'NHÁP',
  'statusClosed': 'ĐÃ ĐÓNG',
  'statusActive': 'ĐANG MỞ',
  'statusPending': 'CHỜ DUYỆT',
  'couldNotSaveJob': 'Không thể lưu tin tuyển dụng.',
  'experienceLevel': 'Cấp bậc kinh nghiệm',
  'entryLevel': 'Mới bắt đầu',
  'midLevel': 'Trung cấp',
  'seniorLevel': 'Cao cấp',
  'leadLevel': 'Trưởng nhóm',
  'clearAll': 'Xóa tất cả',
  'showResults': 'Xem kết quả',
  'enterLocationHint': 'Nhập thành phố, tỉnh hoặc quốc gia',
  'jobSaved': 'Đã lưu công việc!',
  'addedToFavorites': 'Đã thêm vào\ndanh sách yêu thích',
  'applicantsSoFar': 'ứng viên cho đến nay',
  'resumePreview': 'Xem trước Hồ sơ',
  'filesCount': 'TỆP',
  'replacedSuccess': 'Thay thế thành công',
  'couldNotOpenUrl': 'Không thể mở URL CV',
  'uploadedLabel': 'Đã tải lên',
  'applicationTimeline': 'Tiến trình ứng tuyển',
  'applicationSubmitted': 'Đã gửi hồ sơ',
  'underReview': 'Đang xét duyệt',
  'shortlistedInterview': 'Hồ sơ tiềm năng/Phỏng vấn',
  'decision': 'Quyết định',
  'yourApplication': 'Hồ sơ của bạn',
  'attachedResume': 'Hồ sơ đính kèm',
  'withdrawConfirmMessageUndo':
      'Bạn có chắc chắn muốn rút hồ sơ? Hành động này không thể hoàn tác.',
  'pendingReview': 'Chờ xét duyệt',
  'employerReviewing': 'Nhà tuyển dụng đang xem',
  'interviewInvited': 'Đã mời phỏng vấn',
  'acceptedHired': 'Đã trúng tuyển',
  'notSelected': 'Không phù hợp',
  'withdrawnByYou': 'Bạn đã rút hồ sơ',
  'currentStatus': 'Trạng thái hiện tại',
  'applicationStatus': 'Trạng thái ứng tuyển',
  'negotiableSubtitle': 'Cho ứng viên biết mức lương có thể thỏa thuận.',

  // Deleted Users
  'restoreAccountTitle': 'Khôi phục tài khoản',
  'restoreAccountConfirm': 'Bạn muốn khôi phục tài khoản',
  'restoreAccountNormal': 'Tài khoản này sẽ hoạt động lại bình thường.',
  'restoreAction': 'Khôi phục',
  'restoreSuccess': 'Đã khôi phục tài khoản thành công.',
  'restoreError': 'Lỗi khi khôi phục.',
  'hardDeleteTitle': 'Xóa VĨNH VIỄN',
  'hardDeleteConfirm': 'CẢNH BÁO: Hành động này sẽ xóa vĩnh viễn',
  'hardDeleteUndone':
      'khỏi cơ sở dữ liệu Supabase và không thể hoàn tác. Bạn có chắc chắn không?',
  'hardDeleteAction': 'Xóa vĩnh viễn',
  'hardDeleteSuccess': 'Đã xóa vĩnh viễn khỏi hệ thống.',
  'hardDeleteError': 'Lỗi khi xóa vĩnh viễn.',
  'accountTrashTitle': 'Thùng rác tài khoản',
  'emptyTrash': 'Thùng rác trống',
  'rolePrefix': 'Vai trò:',

  // Employer detail & popup
  'employerDetail': 'Thông tin nhà tuyển dụng',
  'companySize': 'Quy mô công ty',
  'industryLabel': 'Lĩnh vực',
  'contactInfo': 'Thông tin liên hệ',
  'copyAddressSuccess': 'Sao chép địa chỉ thành công!',
  'chatWithEmployer': 'Nhắn tin với nhà tuyển dụng',
  'noDescriptionProvided': 'Nhà tuyển dụng chưa cập nhật thông tin giới thiệu chi tiết.',
  'phoneLabel': 'Số điện thoại',
  'emailLabel': 'Email',
  'websiteLabel': 'Website',
  'addressLabel': 'Địa chỉ',
  'noPhone': 'Không có số điện thoại',
  'noEmail': 'Không có email',
  'noWebsite': 'Không có website',
  'noAddress': 'Không có địa chỉ',
  'recruiter': 'Người đăng tuyển',
  'viewDetails': 'Chi tiết',
  'messageNow': 'Nhắn tin ngay',
  'employerLabel': 'Nhà tuyển dụng',
  'activeNow': 'Đang hoạt động',
  'employerAccountNotFound': 'Không tìm thấy tài khoản nhà tuyển dụng này.',
  'emailSubjectQuery': 'Hỏi về vị trí tuyển dụng',
  'featureInDevelopment': 'Tính năng này đang trong quá trình phát triển. Vui lòng quay lại sau!',
  'featureInDevelopmentTitle': 'Sắp ra mắt',
  // kinh nghiệm + kĩ năng
  'addExperience': 'Thêm kinh nghiệm',
  'companyName': 'Tên công ty',
  'companyNameHint': 'VD: Google',
  'position': 'Vị trí',
  'positionHint': 'VD: Flutter Developer',
  'startDate': 'Ngày bắt đầu',
  'endDate': 'Ngày kết thúc',
  'endDateHint': 'Để trống nếu đang làm',
  'describeRole': 'Mô tả công việc của bạn...',
  'fillRequiredFields': 'Vui lòng điền đầy đủ thông tin bắt buộc',
  'endDateBeforeStart': 'Ngày kết thúc phải sau ngày bắt đầu',
  'workExperience': 'Kinh nghiệm làm việc',
  'noExperienceYet': 'Chưa có kinh nghiệm.\nNhấn Thêm để bắt đầu.',
  'deleteExperience': 'Xóa kinh nghiệm',
  'deleteExperienceConfirm': 'Bạn có chắc muốn xóa kinh nghiệm này?',
  'add': 'Thêm',
  'skillLabel': 'Kỹ năng',
  'skillSearchHint': 'Gõ để tìm kỹ năng...',
  'responsesTabLabel': 'Phản hồi',
  'systemTabLabel': 'Hệ thống',
  'reportsTabLabel': 'Báo cáo',
  'noNotificationsMessage': 'Chưa có thông báo nào',
  'unableToLoadNotifications': 'Không thể tải thông báo',
  'markAllAsRead': 'Đánh dấu tất cả là đã đọc',
  'allMarkedAsReadMessage': 'Đã đánh dấu tất cả thông báo là đã đọc',

  // Employer Dashboard / Profile / Edit Profile
  'companyManagement': 'QUẢN LÝ DOANH NGHIỆP',
  'billingAndSecurity': 'THANH TOÁN & BẢO MẬT',
  'companyProfile': 'Hồ sơ công ty',
  'viewPublicCompanyPage': 'Xem trang công ty công khai',
  'companyInformation': 'Thông tin công ty',
  'logoBannerDescription': 'Logo, ảnh bìa và mô tả',
  'teamManagement': 'Quản lý đội ngũ',
  'manageRecruitersPermissions': 'Quản lý tuyển dụng & quyền hạn',
  'billingSubscription': 'Thanh toán & Gói dịch vụ',
  'managePlansInvoices': 'Quản lý gói cước và hóa đơn',
  'accountSecurity': 'Bảo mật tài khoản',
  'password2faActivity': 'Mật khẩu, 2FA, hoạt động đăng nhập',
  'helpCenterDesc': 'Tài liệu và hỗ trợ trực tuyến',
  'contactUsDesc': 'Liên hệ với đội ngũ hỗ trợ',
  'verifiedEmployer': 'Nhà tuyển dụng xác minh',
  'saveChanges': 'Lưu thay đổi',
  'logoUploadSuccess': 'Tải lên logo thành công!',
  'logoUploadFailed': 'Tải lên logo thất bại. Vui lòng thử lại.',
  'profileUpdateSuccess': 'Cập nhật hồ sơ công ty thành công!',
  'profileUpdateFailed': 'Cập nhật hồ sơ thất bại. Vui lòng thử lại.',
  'isFieldsRequired': 'là bắt buộc',

  // Employer Messages
  'allMessagesSection': 'Tất cả tin nhắn',
  'chatWithCandidatesPartners': 'Trò chuyện với ứng viên & đối tác',
  'noMessagesDescription': 'Chưa có tin nhắn nào',
  'unableToLoadMessages': 'Không thể tải tin nhắn',

  // Employer Applicants / Candidate Profile
  'profileSummary': 'Tóm tắt hồ sơ',
  'noProfileSummary': 'Chưa cập nhật tóm tắt hồ sơ.',
  'seniorityLabel': 'Cấp bậc',
  'roleLabel': 'Vai trò',
  'educationLabel': 'Học vấn',
  'salaryLabel': 'Mức lương',
  'contactLabel': 'Liên hệ',
  'dateOfBirthLabel': 'Ngày sinh',
  'notProvided': 'Chưa cung cấp',
  'noExperienceProvided': 'Chưa cập nhật kinh nghiệm làm việc.',
  'backgroundSection': 'Thông tin nền',
  'roleMatchLabel': 'Độ khớp vai trò',
  'genderLabel': 'Giới tính',
  'userIdLabel': 'ID người dùng',
  'noSkillsProvided': 'Chưa cập nhật kỹ năng.',
  'noResumeUploaded': 'Chưa tải lên CV.',
  'copyResumeLink': 'Sao chép liên kết CV',
  'resumeLinkCopied': 'Đã sao chép liên kết CV!',
  'shortlistSuccess': 'Đã đưa ứng viên vào danh sách tiềm năng.',
  'shortlistFailed': 'Không thể đưa ứng viên vào danh sách tiềm năng.',
  'rejectCandidateTitle': 'Từ chối ứng viên?',
  'rejectCandidateConfirm': 'Hành động này sẽ đánh dấu ứng viên là đã bị từ chối cho công việc này.',
  'rejectSuccess': 'Đã từ chối ứng viên thành công.',
  'rejectFailed': 'Từ chối ứng viên thất bại.',

  // Employer Job Applicants
  'applicantsSubtitle': 'ỨNG VIÊN',
  'searchCandidatesHint': 'Tìm kiếm ứng viên...',
  'sortLabel': 'Sắp xếp:',
  'sortNewest': 'Mới nhất',
  'sortAiHigh': 'Điểm AI cao',
  'sortAiLow': 'Điểm AI thấp',
  'invalidJobId': 'ID công việc không hợp lệ.',
  'failedToLoadApplicants': 'Không thể tải danh sách ứng viên.',
  'noApplicantsFound': 'Chưa có ứng viên nào ứng tuyển cho công việc này.',
  'noApplicantsMatch': 'Không tìm thấy ứng viên phù hợp với tìm kiếm.',

  // Employer Talent Search
  'recommendedCandidates': 'ỨNG VIÊN ĐỀ XUẤT',
  'findTalentTitle': 'Tìm kiếm nhân tài',
  'refreshCandidatesTooltip': 'Tải lại danh sách ứng viên',
  'searchTalentHint': 'Kỹ năng, chức danh hoặc tên',
  'noCandidatesMatching': 'Không tìm thấy ứng viên nào phù hợp với tiêu chí của bạn.',
  'resetFilters': 'Đặt lại bộ lọc',
  'noSkillsListed': 'Chưa cập nhật kỹ năng',

  // Employer Interview Schedule / Detail / Edit / Create
  'createInterviewTitle': 'Tạo lịch phỏng vấn',
  'editInterviewTitle': 'Sửa lịch phỏng vấn',
  'interviewDetailTitle': 'Chi tiết lịch hẹn',
  'pleaseSelectJob': 'Vui lòng chọn job',
  'pleaseSelectCandidate': 'Vui lòng chọn ứng viên',
  'pleaseSelectDateTime': 'Vui lòng chọn ngày và giờ',
  'recruitingPosition': 'Vị trí tuyển dụng *',
  'selectJobHint': 'Chọn job',
  'candidateRequired': 'Ứng viên *',
  'selectCandidateHint': 'Chọn ứng viên',
  'interviewDateLabel': 'Ngày phỏng vấn *',
  'selectDateHint': 'Chọn ngày',
  'interviewTimeLabel': 'Giờ phỏng vấn *',
  'selectTimeHint': 'Chọn giờ',
  'interviewTypeLabel': 'Hình thức',
  'locationHint': 'Nhập địa điểm',
  'contactPersonHint': 'Tên người liên hệ',
  'notesHint': 'Ghi chú thêm',
  'updateInterviewSuccess': 'Cập nhật lịch phỏng vấn thành công!',
  'deleteInterviewConfirm': 'Bạn có chắc muốn xóa lịch này không?',
  'deleteInterviewTitle': 'Xóa lịch hẹn',
  'deleteSuccessMsg': 'Đã xóa lịch hẹn',
  'candidateConfirmed': 'Ứng viên đã xác nhận',
  'candidateRejected': 'Ứng viên đã từ chối',
  'candidateReschedule': 'Ứng viên yêu cầu đổi lịch',
  'candidatePending': 'Chờ phản hồi từ ứng viên',
  'rescheduleProposal': 'Ngày/giờ đề xuất: ',
  'rescheduleConfirmSuccess': 'Đã xác nhận đổi lịch!',
  'rescheduleRejectSuccess': 'Đã từ chối yêu cầu đổi lịch',
};
